### ISSUE TITLE
Wifi not working from fullpageos-network file

### ISSUE THREAD

**Issue by jorgeiglesiasca** [guysoft/FullPageOS#10]
Tried to configure WIFI from the fullpageos-network file but does not work.  

If i go to X  server and configure from graphical screen it works and remains configurated for next reboots.

If i go to /etc/network/interfaces and edit there the same lines i have in fullpageos-network  it works. 

uncommented the lines IFACE - SSID - PASSWORD

**Comment by linuxundich** [comment]
When you look closely at the boot messages you notice, that FullPageOS looks for a /boot/octopi-network.txt. When you copy /boot/fullpageos-network.txt to /boot/octopi-network.txt the wlan starts up -- i guess this has something to do with the fact that FullPageOS is built on Octopi.

**Comment by guysoft** [comment]
@linuxundich Ok thats a good pointer, I located the problem!
Sould be fixed in the next version of FullPageOS.
In the meantime you can report if running this fixes it:

    sudo sed -i 's/octopi/fullpageos/g' /root/bin/map_iface

**Comment by guysoft** [comment]
Update: you also need to change octopi to fullpageos in the fullpageos-network.txt file.

Has anyone got his to work so far?

**Comment by guysoft** [comment]
Latest nightly fixes the issue, tested and confirmed:
http://docstech.net/FullPageOS/nightly/2015-12-22_2015-11-21-fullpageos-jessie-0.6.0.zip
