### ISSUE TITLE
DNS not resolving

### ISSUE THREAD

**Issue by conrad9900** [guysoft/FullPageOS#101]
my network file looks like this:
auto eth0:1
iface eth0:1 inet dhcp
dns-nameservers 192.168.0.10
#address 192.168.0.102
#netmask 255.255.255.0
#broadcast 192.168.0.210

I have a server named dps that will not show up, all i get is the chromium settings tab open, asking to import bookmarks

**Comment by guysoft** [comment]
What does /etc/resolv.conf looks like?

**Comment by conrad9900** [comment]
How do i access /etc? i cannot access the pi from its IP address or the .local address. all i get is a placeholder page that has not yet been setup

**Comment by conrad9900** [comment]
Sorry got it sorted, resolv.conf looks like the following:

nameserver 192.168.0.10
