### ISSUE TITLE
How to run zbartools with OS

### ISSUE THREAD

**Issue by conrad9900** [guysoft/FullPageOS#103]
I have FullpageOS running smooth now, i do however require a program to run in the background. 
Zbartools is needed to scan qr codes. the only code to start it is ~$ zbarcam
Is this possible?

**Comment by guysoft** [comment]
1. Clean and organized way:
Create a systemctl service
2. Quick and dirty:
Just add the line in to ``/home/pi/scripts/run_onepageos``

**Comment by conrad9900** [comment]
Will this run in the background with no consoles showing?

**Comment by guysoft** [comment]
Put it at the top before the while with a ``&`` at the end
