### ISSUE TITLE
AutoFill/Saved passwords

### ISSUE THREAD

**Issue by ShinPKSK** [guysoft/FullPageOS#105]
I'm using FullPageOS as a timeclock kiosk. It works great except that Chromium AutoFill is saving emails, User IDs and passwords of users that log in. Is there any way to disable these behaviours in FullPage? In chrome I'd just go to chrome://settings but that doesn't work in FullPage, it just crashes then go to the new tab page instead.

**Comment by guysoft** [comment]
FullPageOS is running chromium. You can ctl+t to open a new window, then
put chrome://settings.
Does that work?

**Comment by ShinPKSK** [comment]
Perfect, using the standard chromium settings menu I was able to disable autofill and saved passwords. Thank you!
