### ISSUE TITLE
Connect to Multiple Wifi SSID's?

### ISSUE THREAD

**Issue by trawlerguy** [guysoft/FullPageOS#109]
Have tried editing fullpageos-network.txt with multiple SSID's.  When the following is in that file by itself, it works as expected:
iface wlan0-fullpageos inet dhcp
wpa-ssid "Offices1"
wpa-psk "thisismykey"

Have tried adding in additional SSID's in a couple of different ways, but seems the "wlan0-fullpageos" interface name is necessary...

Have tried, this doesn't work: 
iface wlan0-fullpageos inet dhcp
wpa-ssid "Offices1"
wpa-psk "thisIsmyKey1"
iface wlan1-fullpageos inet dhcp
wpa-ssid "Offices2"
wpa-psk "thisismykey2"
iface wlan2-fullpageos inet dhcp
wpa-ssid "Offices3"
wpa-psk "thisismykey"

Any ideas on how to get FullPageOS working with multiple SSID's?

**Comment by guysoft** [comment]
Please follow this:
http://raspberrypi.stackexchange.com/questions/37920/how-do-i-set-up-networking-wifi-static-ip-address/37921#37921
You need to use ``/etc/wpa_supplicant/wpa_supplicant.conf`` and not the ``fullpageos-network.txt`` file for this.
