### ISSUE TITLE
need flash

### ISSUE THREAD

**Issue by nygkin** [guysoft/FullPageOS#112]
Everything was working great until I tried to install flash
pi@receiving_display:~/.config $ sudo apt-get install rpi-chromium-mods

now all I have is a black screen.  
I can reinstall the OS that is no big deal but I will need flash installed.
Any ideas?

**Comment by guysoft** [comment]
1. What version of FullPageOS are you using?
2. If you are not using 0.7.0 RC1 then please do, it has flash supported out of the box.

**Comment by nygkin** [comment]
Got it working.  thanks!

**Comment by guysoft** [comment]
@nygkin Can you explain please what you did to get flash working?
