### ISSUE TITLE
No hdmi output after boot

### ISSUE THREAD

**Issue by mgjuhler** [guysoft/FullPageOS#113]
I get no picture on my hdmi output after boot. the device boots up fine and when it is finished, its just blank screen. it works like 2 out 10 times :(

Build: fullpageos-jessie-lite-0.7.0_RC1 (Nightly)
Pi version: 3 B

**Comment by guysoft** [comment]
Do you have a mouse cursor? It sounds like chromium didn't start.

**Comment by mgjuhler** [comment]
Hi, 
I just tested on some more screens and have found out that it works as it should. Every time I restart my PI is come up again as it should. So it must obviously be the monitor I tested on having a bug or the like. Sorry for the inconvenience.
