### ISSUE TITLE
Raspberry Pi Zero W

### ISSUE THREAD

**Issue by chrisvdb** [guysoft/FullPageOS#117]
There are a number of Github issues that imply that the Raspberry Pi Zero is (currently) not supported. I have however not found any statement regarding the new Raspberry Pi Zero W. Is this one supported by FullPageOS?

The Raspberry Pi Zero W has an ARM 11 CPU running at 1GHz ([link](https://www.raspberrypi.org/magpi/pi-zero-w/)).

**Comment by guysoft** [comment]
Well, I am not entirely sure, and since I have no hardware to test I really can't tell.
However, I can build a new nightly build (which are done on demand). And you can test for yourself and report what the status is.

Technically from what I can read the Raspberry Pi Zero W should not be able to run Armv7 instructions, but since then we moved to use chromium build supplied by the rip-foundation, and they might have fixed something, so its worth testing.

[I've started a build](http://gnethomelinux.com:8080/job/FullPageOS/52/console), when its ready an uploaded I'll link to it here so you can test for yourself.

**Comment by chrisvdb** [comment]
Excellent, I will test tomorrow or coming weekend and report back.

**Comment by chrisvdb** [comment]
Looks like the build has finished. The link at the bottom does not work, though.

**Comment by guysoft** [comment]
Here you go:
https://github.com/guysoft/FullPageOS/issues/118

**Comment by chrisvdb** [comment]
I have tried the image without any configuration:

- booted fine
- flashed a square with color gradients for a second
- black screen

What can I do to help debug? Would it help if I sponsor a Raspberry Pi Zero W device?

**Comment by chrisvdb** [comment]
Quick update: I have tried the latest [raspian build](https://downloads.raspberrypi.org/raspbian_latest) on my Raspberry Pi Zero W. Everything seems to be functional, including Chromium.

**Comment by chrisvdb** [comment]
I have also tested RC1: the screen remained entirely black throughout, not even showing any boot messages in console mode. So, from that perspective RC2 is an improvement over RC1.

**Comment by thundergreen** [comment]
Is it possible to have a raspberry Pi1 image?

**Comment by guysoft** [comment]
@thundergreen 1. you are off topic
2. No, see https://github.com/guysoft/FullPageOS/issues/43

**Comment by chrisvdb** [comment]
Hi @guysoft, is there anything more I can do at this time? For example test a newer build or provide debugging information on the latest build. In the latter case, which information would be helpful?

**Comment by guysoft** [comment]
You can try taking RC2 and FIGURE OUT why lightdm does not start there. There is development work to do which I am not reaching. Its beyond just testing.

**Comment by chrisvdb** [comment]
I'm planning to do some testing/debugging this weekend. Would you be able to create a new build based on the latest Raspian version?

**Comment by guysoft** [comment]
Building, tough RC2 should also work for testing. Little differences. anyway will post a nightly when ready

**Comment by chrisvdb** [comment]
@guysoft could you please post the nightly?

**Comment by chrisvdb** [comment]
I tried RC3 this morning... same or similar result: blank screen when the graphical environment should be loaded. I'm traveling the next few weeks, so might not be able to test more.

**Comment by chrisvdb** [comment]
I have uploaded the logs [here](https://filebin.ca/3RN62gngzBux/RaspberryPiZeroWLogs.zip).

**Comment by guysoft** [comment]
In that case the RaspberryPi Zero is ARMc6 and is not supported

**Comment by chrisvdb** [comment]
Hi guysoft, I'm a bit confused... Chromium on the latest Raspbian works perfectly on the Raspberry Zero W, so why could FullPageOS not work as well?

**Comment by mecatulo** [comment]
touching this 6 years later, I have a Pi Zero W and I'm getting an error stating that Chromium isn't supported on the RPi Zero W.

is there a way to use a different browser?

**Comment by guysoft** [comment]
Zero W is still not supported.
You can try building FullPageOS with firerfox. 
Its a project asked about here and no one picked up the task:
https://github.com/guysoft/FullPageOS/issues/340
