### ISSUE TITLE
Set Screen to Portrait mode

### ISSUE THREAD

**Issue by Protons** [guysoft/FullPageOS#125]
Hi, I am trying to set the screen to be portrait mode. Can someone tell me how to do it? I tried to find any information about it, but can't seem to see anything with regards to do that. Using FullPageOS Wheezy 0.5.

**Comment by guysoft** [comment]
1. Duplicate of https://github.com/guysoft/FullPageOS/issues/84
2. You should really move to 0.6 or 0.7.0RC1

**Comment by Protons** [comment]
Thank You so soooo much for this custom OS. It is exactly what I needed for my work.

**Comment by guysoft** [comment]
See https://github.com/guysoft/FullPageOS/issues/137 , Raspberrypi Kernel team is fixing a problem
