### ISSUE TITLE
Keys are incorrect. @ and "

### ISSUE THREAD

**Issue by FatManLovesPi** [guysoft/FullPageOS#129]
Does anyone know how to fix the @ and "? They are showing up reversed, so when I try to type @, I get the " symbol and vice versa.

Thanks

**Comment by rawlk** [comment]
use "sudo raspi-config" to set the Localisation Options:
(assuming you're in the us) 
Change Locale:
  -> en_us.utf-8 utf-8
  -> Default locale for system: en_US.UTF-8
Change Keyboard Layout:
 -> Generic 104-key PC
 -> English (US)
 -> No AltGr key
 -> No compose key
 -> (your choice)

After a reboot, this fixed it for me.

While you're in there, might as well update your password and resize the root partition if you haven't already.

**Comment by guysoft** [comment]
Closing if no answer (also thanks @rawlk for detailed instructions)

**Comment by FatManLovesPi** [comment]
@rawlk Thanks for that. I ended up changing the default keyboard file to "us"

sudo nano /etc/default/keyboard
Change gb to us
