### ISSUE TITLE
Static address wont take..keeps getting DHCP

### ISSUE THREAD

**Issue by conrad9900** [guysoft/FullPageOS#130]
fullpageos-network looks like the following:

iface eth0:1 inet static
address 192.168.0.80
netmask 255.255.255.0
broadcast 192.168.0.210
domain profile.local
dns-nameservers 192.168.0.10

However it keeps getting a DHCP address..somehow

**Comment by guysoft** [comment]
See https://github.com/guysoft/OctoPi/issues/202

Also - best practice is to set your router to allocate a specific address and not to force one from the Pi side

**Comment by conrad9900** [comment]
Thanks

**Comment by guysoft** [comment]
Closing if no further information
