### ISSUE TITLE
Not booting when screen rotation is enabled with GPU

### ISSUE THREAD

**Issue by MattiasTR** [guysoft/FullPageOS#137]
#### What were you doing?
I wanted to change the rotation of the screen by 90 degrees. I entered "display_rotate=1" in /boot/config.txt.

#### What did you expect to happen?
The Raspberry Pi 2 Model B should boot with the screen rotated 90 degrees

#### What happened instead?
The activity LED blinked a few times at power on, then nothing happens. The monitor leaves sleep mode, but the screen is black. No debug output is coming on the serial interface.

#### Was there an error message displayed? What did it say?
No error messages, just a blank black screen.

#### Version of FullPageOS?
2017-06-24_2017-06-21-fullpageos-jessie-lite-0.7.0.zip

I have changed the memory split to give the GPU both 128 and 256mb, but there was no difference. Commenting the "display_rotate=1" in the config.txt makes the RPi boot normally. Tested on both RPi 2 and RPi 3 with the same result.

Rotating the screen works on a NOOBS install of Raspbian.

**Comment by guysoft** [comment]
Try booting normally and removing the GPU acceleration first as described
in the release notes of 0.7.0

**Comment by MattiasTR** [comment]
Where can I find the release notes for 0.7.0?

**Comment by guysoft** [comment]
In the release tab:
https://github.com/guysoft/FullPageOS/releases/tag/0.7.0

**Comment by MattiasTR** [comment]
Thank you.

I tested turning off the GPU acceleratin and verified that it was off in Chromium, then rotated the display and the RPi booted as intended with the screen rotated.

Do you want me to close this issue with the resolution to turn off GPU acceleration or leave it open until a future release fixes it?

**Comment by guysoft** [comment]
Its a Raspbian issue. Their GPU driver apparently doesn't support rotation.
This bug should be reported to the raspberrypi linux kernel at:
https://github.com/raspberrypi/linux/issues

And the driver you need to report about is called vc4-kms-v3d

**Comment by guysoft** [comment]
Huh, looks like they are pushing fixes 🥇

**Comment by guysoft** [comment]
Fixes should be in 0.8.0 nightly, you are welcome to test and report back:
http://unofficialpi.org/Distros/FullPageOS/2017-06-24_2017-06-21-fullpageos-jessie-lite-0.7.0.zip
http://unofficialpi.org/Distros/FullPageOS/2017-06-24_2017-06-21-fullpageos-jessie-lite-0.7.0.zip.md5

**Comment by MattiasTR** [comment]
I tested the nightly build found hereon a RPi3:
[http://unofficialpi.org/Distros/FullPageOS/nightly/2017-09-18_2017-09-07-fullpageos-stretch-lite-0.8.zip]
[http://unofficialpi.org/Distros/FullPageOS/nightly/2017-09-18_2017-09-07-fullpageos-stretch-lite-0.8.zip.md5]

I added the line "display_rotate=1" in /boot/config.txt

The first cold boot (tested twice, reimaged the SD-card in between) the display is rotated until it automatically reboots, then it ignores the setting in the config.txt on all following cold and warm reboots.

The changing of slides in the default presentation seems to be very slow as well, it looks like it is not using the HW acceleration.

**Comment by guysoft** [comment]
You can test if GPU acceleration is used by:
1. Press ctrl+tab to open a new window
2. Type ``chrome://gpu``

You could post a reply to the kernel team I guess.

**Comment by conrad9900** [comment]
I had a look through the release notes but i am finding it difficult to find a simple command to diable GPU acc. Does someone have a command?

**Comment by guysoft** [comment]
Only via ``raspi-config``. There is no command.  I copied the source code from raspi-config in order to get it to work in the first place.

**Comment by rlucian** [comment]
I've read on this thoroughly but it's not clear whether HW acc is going to be available on rotated desktops.
Right now display-rotate=1 works but only after disabling hardware acceleration, in 0.8.1
Is there any work in progress on having acceleration functional on rotated screens?

**Comment by guysoft** [comment]
There was a commit to the raspberrypi kernel regarding this issue two month ago. You can try updating the kernel and see if it fixes it.

**Comment by Jaxel** [comment]
Where do I disable GPU acceleration in raspi-config?

**Comment by guysoft** [comment]
Second result on google for "raspi-cofig gpi accelerarion" dude: https://docs.eltechs.com/install-and-configure-exagear-desktop/hardware-graphics-acceleration-on-rpi

**Comment by Jaxel** [comment]
Okay, I got the rotation working using `display_rotate=1`... and its much better.

However, the touch screen itself is off. How do i fix this?

**Comment by rlucian** [comment]
try this: https://www.raspberrypi.org/forums/viewtopic.php?t=120793

more precisely, in /boot/config.txt see below the comment on rotating both image and touch interface, didn't test to see if only a value of 2 works, or 1 (90 degrees) as well.
```
display_rotate=0 Normal
display_rotate=1 90 degrees
display_rotate=2 180 degrees
# NOTE: You can rotate both the image and touch interface 180º by entering lcd_rotate=2 instead
display_rotate=3 270 degrees
display_rotate=0x10000 horizontal flip
display_rotate=0x20000 vertical flip
```

**Comment by rlucian** [comment]
After updating kernel with raspi-update, webgl acceleration works even with rotation, but only on FAKE KMS setting.

```
Graphics Feature Status
Canvas: Hardware accelerated
CheckerImaging: Disabled
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Enabled
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
Rasterization: Software only. Hardware acceleration disabled
Video Decode: Software only, hardware acceleration unavailable
Video Encode: Software only, hardware acceleration unavailable
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

**Comment by benyanke** [comment]
I was able to get system-wide screen rotation working. Since it was mentioned but not explicitly  documented above, I will document the exact steps here:

1) sudo raspi-config
2) 7 - Advanced Options
3) A7 - GL Driver
4) G2 - GL (Fake KMS)
5) Reboot

This should allow you to rotate the screen.

**Comment by evandrobts** [comment]
Thanks benyanke! It worked perfectly. Im using fullpageos-stretch-lite-0.8.1 with RPi 3 Model B.

**Comment by guysoft** [comment]
Seems like issue is solved closing.

**Comment by unlucio** [comment]
I installed FullPageOS on a Pi 3b+ I had lying around with "Raspberry Pi Display V1.1", and I'm going a bit crazy trying to rotate the screen where I need it (180°)

So far, these are the results:
`display_rotate=2` --> didn't work
`display_rotate=0x20000 vertical flip` --> didn't work
`display_rotate=2` partially works: the screen starts in the expected orientation, but asap it flashes after the 1st FullPageOS logo, it goes back to the default orientation, and everything ends up upside down :(

https://github.com/user-attachments/assets/78eca1bb-171c-4cf1-81a8-393d765f11dd

And if I try flipping lightdm with `xrandr -o inverted`, my mouse pointer and input go drunk, and it's all flipped:

https://github.com/user-attachments/assets/b43f986a-212c-4712-959f-74eea9c5ae5e

I tried for a week to flip this thing, so I made a bazillion other tries I don't even remember anymore, and now I'm lost
I'm a bit disconcerted by how it can be so complicated to flip a screen, but here I am.
Does anyone know how to get to the end of this?

**Comment by unlucio** [comment]
OMG, I found the "solution"

It's like voodoo:

1) /boot/firmware/cmdline.txt
``` 
console=serial0,115200 console=tty1 root=PARTUUID=ae364ac2-02 rootfstype=ext4 fsck.repair=yes rootwait cfg80211.ieee80211_regdom=IT video=DSI-1:800x480@60,rotate=180
```

2) /boot/firmware/config.txt
```
### add on top
lcd_rotate=2

#[and then everything ellse]
```
3) .xsessionrc
```
#!/bin/sh

export DISPLAY=:0;
export XAUTHORITY=/home/lucio/.Xauthority

OUT=$(xrandr | awk '/^DSI-/{print $1; exit}')
ID=$(xinput list --id-only '10-0038 generic ft5x06 (79)')

echo "ID: $ID, OUT: $OUT"
xrandr --output "$OUT" --rotate inverted
xinput --map-to-output "$ID" "$OUT"
```

4) reboot

5) wait for the screen to go crazy

![Image](https://github.com/user-attachments/assets/8b0275c1-5007-454b-87a3-1303a21ddcc5)

6) proceeded furiously, sliding your finger on the screen until it decides to show the picture

7) enjoy

😳
