### ISSUE TITLE
Nothing on boot

### ISSUE THREAD

**Issue by cidlibrary** [guysoft/FullPageOS#138]
#### What were you doing?
Booting for the first / second time

This is on a Pi Zero W. Is this supported?

#### What did you expect to happen?
Booting to a full screen
#### What happened instead?
Black screen after first boot that resized the partition
#### Was there an error message displayed? What did it say?
None
#### Version of FullPageOS?
0.7.0
[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]
However, I do get CLI access, it does allow SSH into the box.

**Comment by guysoft** [comment]
Pi Zero W is not supported, see https://github.com/guysoft/FullPageOS#requirements
