### ISSUE TITLE
Chromium config

### ISSUE THREAD

**Issue by beathorst** [guysoft/FullPageOS#14]
Where can I find the config for the autoloading chromium?

**Comment by guysoft** [comment]
It should be located at ``~/.config/chromium/Default``
But I am not sure what you can do before the profile is generated.

**Comment by guysoft** [comment]
@beathorst wait, I just re-read this - you mean you want the config beloning to Chromium, or the configuration that makes chromium start at boot?

**Comment by guysoft** [comment]
Closing if no reply

**Comment by facetime88** [comment]
Where to edit the chromium config. I'd like to launch chromium with flags auto reload enabled: chrome://flags/#enable-offline-auto-reload

**Comment by guysoft** [comment]
Thanks @facetime88, but still closing because no reply from OP
