### ISSUE TITLE
Editing the fullpageos.txt from Pi

### ISSUE THREAD

**Issue by sng1** [guysoft/FullPageOS#141]
Hi,  Is there a way to edit direct the fullpageos.txt directly from the Pi while it's running?

ctrl + alt + F1

Where do I go from there to get to that file and edit it to change the URL?

Thanks

**Comment by guysoft** [comment]
You can if you open a terminal and edit it.
You can't via the browser, that's why we ship with FullPageDashboard which
lets you add pages.

**Comment by sng1** [comment]
FullPageDashboard is locally on the Pi?

What's the path to find  fullpageos.txt from the command line?

**Comment by sng1** [comment]
I guess nano fullpageos.txt   will do the trick!!!    I'll have to play around with it!   Thanks

**Comment by guysoft** [comment]
It says so in the readme under the feature list:
https://github.com/guysoft/FullPageOS/blob/devel/README.rst#features
