### ISSUE TITLE
Bad Video When Rebooting Pi

### ISSUE THREAD

**Issue by sng1** [guysoft/FullPageOS#145]
Only problem I have is when I reboot the Pi3 the picture goes all over the screen and rolls up and down and right to left.   Looks like wrong fps.  I went through all the settings in config.txt regarding the HDMI.  When I start from scratch everything looks fine but soon as I reboot the Pi everything goes all over the place.  I can run Ubuntu Matte no problem and other iso but this only happen with FullPageOS.  What could be the issue?

**Comment by guysoft** [comment]
Do you a url with an example?

**Comment by guysoft** [comment]
Closing if no reply
