### ISSUE TITLE
FullPageOS booting to Debian 8 login screen. 

### ISSUE THREAD

**Issue by cesarzapatawfm** [guysoft/FullPageOS#146]
#### What were you doing?

nothing. My page has been working for weeks.

#### What did you expect to happen?
work as the other older verions of fullpageos
#### What happened instead?
instead of displaying my page, fullpageos is booting to a Debian 8 login screen. 

#### Was there an error message displayed? What did it say?
no error. I tried loggin with the pi login but it just reverts back to the Debian 8 screen.

#### Version of FullPageOS?

Could not get it as I had to reformat. 

#### Screenshot(s) showing the problem:

login similar to this one 
http://www.cnx-software.com/wp-content/uploads/2015/09/Orange_PI_Debian_8_Login.jpg

**Comment by guysoft** [comment]
Is there a way to reproduce this?

**Comment by guysoft** [comment]
Closing, no reply

**Comment by guthubuser** [comment]
i can confirm this. this also happens to my installation. 
The debian screen appears and no change to revert. Where are the credentials stored? how is the autologin done?
I can login with root account and then the scipt continues

**Comment by guysoft** [comment]
@guthubuser please use the nightly with debian 9.

**Comment by guthubuser** [comment]
after a few reboots the same thing happened with debian 9. Can you tell me how the autologin is done? it is NOT in the /etc/lightdm/lightdm.conf 
[SeatDefaults] 
 autologin-user=pi
 autologin-user-timeout=0

**Comment by guysoft** [comment]
This is the code pn build that handles it, if you upgrade it might get overwritten:
https://github.com/guysoft/CustomPiOS/blob/CustomPiOS/src/modules/gui/end_chroot_script

**Comment by ianpowell2017** [comment]
I had the same issue.  I had created a new user and password overwriting the default 'pi' user.
I re-flashed the image using the default 'pi' user and it worked again.
I hope this helps someone

**Comment by rackycz** [comment]
I have similar problem in 2026 in a network that seems to be slower. AI answered: 

> FullPageOS waits for an internet connection before opening the browser. If the network is slow or unavailable, it may stall at the splash screen or show a white screen
> 
> Create file named /boot/check_for_httpd to disable the initial check for an Internet connection, allowing it to boot offline

It is not easy to simulate the problem so I do not know yet if it really helps.
Search for "check_for_httpd" in the repository.
