### ISSUE TITLE
Booting to Kiosk mode but cycling between three Chromium tabs?

### ISSUE THREAD

**Issue by esaruoho** [guysoft/FullPageOS#148]
Hi, I'm trying to figure out if I could get FullpageOS to boot up and start three Chromium tabs in Kiosk mode, but then actually switch between displaying tab1, tab2, tab3 at a given time? Like every minute, go from tab1 to tab2.. or tab2 to tab3.. or tab3 to tab1. kinda like a page-carousel. Would FullpageOS allow for this kind of behaviour?

**Comment by guysoft** [comment]
No apart from FullPageDashboard there is no such functionality, you are welcome to research and report here. I just never had use for this.

**Comment by esaruoho** [comment]
Unfortunately FullPageDashboard is kind of an oxymoron since it is not an actual full page. I'm not PHP savvy so please don't repeat your _suggestion_ of "stop using it or code it better"

**Comment by guysoft** [comment]
I'll would also accept a pull request of a dashboard that is coded better in a different language. FullPageDashboard is not maintained anymore by its developer.
