### ISSUE TITLE
How to schedule daily boots (every 24 hours)

### ISSUE THREAD

**Issue by esaruoho** [guysoft/FullPageOS#149]
I have a Geckoboard dashboard running on FullPageOS - thing is that every few days, the whole setup will crash and refuse to continue fetching data from the site. How do I make FullPageOS reboot every 24 hours (at midnight, for instance)? 

I've tried to disable audio and disable the raspicam, hoping that that will somehow help. I'm not sure where else to go.

```
# Enable audio (loads snd_bcm2835)
dtparam=audio=off
# enable raspicam
start_x=0
dtoverlay=vc4-kms-v3d
```

**Comment by guysoft** [comment]
1. What version of FullPageOS are you using?
2. You could try and disable GPU acceleration
3. You could set a cronjob

**Comment by guysoft** [comment]
Hey, I've been testing the latest nightly of 0.8.0, and its MUCH more stable than 0.7.0, I also had "aww snap" crashes that stopped, suggest you try that.

**Comment by digitalknk** [comment]
`sudo su`
`crontab -e`

add this line
`0 5 * * * /sbin/shutdown -r now`

save and exit

Now it will reboot everyday at 5AM

**Comment by guysoft** [comment]
Closing due to no reply since September of OP, also 0.8.1 is really much more stable.

**Comment by esaruoho** [comment]
@digitalknk thanks for this, i've set it to work and it works. thanks a lot
i guess i need to install 0.8.0 or something..
