### ISSUE TITLE
Nightly 2017-08-16 black screen with cursor

### ISSUE THREAD

**Issue by ludagoo** [guysoft/FullPageOS#153]
I have a stable version on on sd card and a nightly on a other one. the stable works great except it doesn't handle a web app with lots of animation well. I wanted to see if stretch would do any better. I can't get the nightly 2017-08-16-fullpageos-stretch-lite-0.8 to load the page. Any ideas?

**Comment by guysoft** [comment]
I didn't get time to test it myself. And I wont for two weeks because I an flying tomorrow to Burning Man. 
Can you post the detailed explanation that is given in a new bug? its there for a reason.
Because I want to know:
1. what stable version are you using - because if its 0.6.0 its irrelevant. And 0.7.0 would rule out a GPU problem
2. A screenshot would help - is there a cursor on the top left of the screen?

**Comment by guysoft** [comment]
Sounds like same behavior of https://github.com/guysoft/FullPageOS/issues/152#issuecomment-323745463

**Comment by guysoft** [comment]
Ok, that nightly is messed up, 
It failed because of this bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845720
rebuilding

**Comment by ludagoo** [comment]
Where you able to kick off the build before leaving

**Comment by guysoft** [comment]
Yes, should have just finished uploading. Check out the nightly folder

**Comment by alanjm99** [comment]
It was uploading got to about 456MB now its disappered

**Comment by ludagoo** [comment]
It's back, only 2/3 the size of the last build... downloading now... we'll see if it works...

**Comment by alanjm99** [comment]
Its still uploading......

**Comment by guysoft** [comment]
The suspense is terrible, I hope it will last.

**Comment by ludagoo** [comment]
Indeed! 😂

**Comment by ludagoo** [comment]
where'd it go... 😂

**Comment by alanjm99** [comment]
Making some progress :) 

sudo apt-get update
sudo apt-get install dirmngr

sudo apt-get install chromium-browser

sudo apt-get purge lightdm
sudo apt-get update
sudo apt-get install lightdm
sudo dpkg-reconfigure lightdm

Now have a login screen

**Comment by ludagoo** [comment]
Then what?

**Comment by ludagoo** [comment]
I built the last commit  695dc37 and it all works great now.

**Comment by it-can** [comment]
@guysoft can you upload a new nightly? The current one is displaying a black screen with a cursor :-(

**Comment by ludagoo** [comment]
@guysoft said:  "I wont for two weeks because I an flying tomorrow to Burning Man." six days ago

**Comment by ludagoo** [comment]
@it-can here is my build for the latest commit... https://goo.gl/fbnhn2

**Comment by it-can** [comment]
@ludagoo wifi doesn't seem to work :-(

**Comment by alanjm99** [comment]
All I get is untrusted/certificate errors

**Comment by ludagoo** [comment]
@it-can do you mean you downloaded and installed the image and can't get the pi to connect to the wifi? If so I haven't tried with wifi. I have it plugged in.

**Comment by it-can** [comment]
@ludagoo yup
