### ISSUE TITLE
FPOS with stretch lite 0.8 - Chromium not loading

### ISSUE THREAD

**Issue by dadeppa** [guysoft/FullPageOS#156]
Hi there,

I downloaded a nightly build (2017-08-18), configured the settings for website and network (dhcp), ssh connection was ok. I have to admit I didn't check the functions on HDMI after this. 

Then I installed LAMP und configured it, at last I installed phpmyadmin - which all was running correct. Then I transfered my old webserver-files and changed the website to the localhost / index.php.

But when I plugged the pi to an HDMI Screen, after console output is just a black screen with a black mouse pointer on loaded. So my guess is, that Chromium is not started properly. Any advice, how to check the configuration for that? 

Thanks in advance!

**Comment by guysoft** [comment]
Please try the latest nightly, tested it myself and it works:
http://unofficialpi.org/Distros/FullPageOS/2017-06-24_2017-06-21-fullpageos-jessie-lite-0.7.0.zip
http://unofficialpi.org/Distros/FullPageOS/2017-06-24_2017-06-21-fullpageos-jessie-lite-0.7.0.zip.md5
