### ISSUE TITLE
How to restart only chromium, not the pi?

### ISSUE THREAD

**Issue by Boscop** [guysoft/FullPageOS#158]
After I wrote a new URL in `/boot/fullpageos.txt`, how can I only restart chromium to load the new URL, without rebooting the pi or interfering with the currently running scripts?

Do I only have to kill `/home/pi/scripts/start_chromium_browser` so that the loop in `scripts/run_onepageos` goes to its next iteration?
What is the best way to kill it without knowing the PID?

Thanks!

**Comment by danielhampton** [comment]
Maybe try something like

sudo pkill -f chromium_browser

Or whatever the process is called

**Comment by guysoft** [comment]
This works (no need for sudo):
```
kill -9 $(ps aux | grep "start_chromium_browser" | grep -v grep | awk '{print $2}')
```
