### ISSUE TITLE
Adding a Tab with a URL doesn't work

### ISSUE THREAD

**Issue by Boscop** [guysoft/FullPageOS#159]
I clicked on `[+]` and added a new tab with url `http://google.com`, but it only shows a blank page, doesn't load the URL, and it also doesn't work with https, or other sites like github.com.
What am I doing wrong?

**Comment by guysoft** [comment]
1. No support in FullPageDashboard for https.
2. ``http://google.com`` does not work, not sure why.

Suggest you use ``/boot/fullpageos.txt`` and not FullPageDashboard.

**Comment by guysoft** [comment]
Closing if no reply

**Comment by Boscop** [comment]
Why doesn't it support https?

**Comment by guysoft** [comment]
I wrote you an answer 6 months ago
