### ISSUE TITLE
ftp

### ISSUE THREAD

**Issue by larrym** [guysoft/FullPageOS#161]
#### What were you doing?

[Please be as specific as possible here]

#### Version of FullPageOS?

[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by larrym** [comment]
Running version 2017-06-24_2017-06-21-fullpageos-jessie-lite-0.7.0, is it possible to transfer a file to the RPi via ftp or sftp?
If it is, what port and credentials?

**Comment by guysoft** [comment]
Same as raspbian, sftp works. Ftp needs installation.

**Comment by guysoft** [comment]
Closing, no description, no response.
