### ISSUE TITLE
Nightly 0.8.0 doesn't work

### ISSUE THREAD

**Issue by Boscop** [guysoft/FullPageOS#162]
I tested 2017-08-24_2017-08-16-fullpageos-stretch-lite-0.8 and it was missing `expect` (for the script setting the vnc password) and it was missing `x11vnc`, and when I installed that, I still couldn't connect via vnc...

**Comment by guysoft** [comment]
Uploaded a nightly that I also tested, this works:
http://unofficialpi.org/Distros/FullPageOS/nightly/2017-09-18_2017-09-07-fullpageos-stretch-lite-0.8.zip

md5:
http://unofficialpi.org/Distros/FullPageOS/nightly/2017-09-18_2017-09-07-fullpageos-stretch-lite-0.8.zip.md5
