### ISSUE TITLE
Turn off monitor at night and turn it on again in the morning

### ISSUE THREAD

**Issue by cweagans** [guysoft/FullPageOS#164]
I think it would be useful to have this option OOTB.

At some configurable time at night, run `tvservice -o` to turn off the display.

In the morning, `tvservice -p` will turn it back on again using preferred settings.

On my pi, `tvservice -p` isn't working for some reason, but I'm choosing to just reboot the pi first thing in the morning instead.

**Comment by guysoft** [comment]
That can all be done in crontab. Just saying.

**Comment by cweagans** [comment]
I know it _can_ be done there. I did it that way.

I'm suggesting that this would be a good thing to do OOTB.

**Comment by guysoft** [comment]
No, because standard behavior is always on. Which is what most people want.
Adding time-based stuff requires you to also set the time zone.

**Comment by cweagans** [comment]
Would you accept an opt-in way to do this through a config file or something? The energy savings is small, but with lots of displays, it will add up.

**Comment by guysoft** [comment]
Yes, you are welcome to send a pull request

**Comment by guysoft** [comment]
Closing if no reply
