### ISSUE TITLE
Nightly build does not work on RaspberryPi 3

### ISSUE THREAD

**Issue by guysoft** [guysoft/FullPageOS#17]
Hey,
I tried FullPageOS image on raspberrypi 3 and it seems to boot in to the wrong GUI environment. Would be nice if anyone else could confirm this.

**Comment by icthelp-spje** [comment]
Hey,

Confirmed here too. Boots to wrong environment, prompts me to login.

**Comment by guysoft** [comment]
That is the only mirror I have that was kindly donated by docstech, I can sync to anywhere else if someone offers storage

**Comment by icthelp-spje** [comment]
I'll contact the CECV and let them know it was incorrectly blocked. 

Will test an earlier build today and let you know.

**Comment by matthova** [comment]
Confirmed.
Same issue for me

**Comment by matthova** [comment]
Just tried with a Raspberry pi2 and had the same issue there as well. It's booting to the debian 8 login screen

**Comment by guysoft** [comment]
Hey all,
The failure was caused because the build was only half built due to a regression, fixes now and tested on the recent nightly, get it at: http://docstech.net/FullPageOS/nightly/2016-05-27_2016-05-10-fullpageos-jessie-lite-0.6.0.zip
md5: 
http://docstech.net/FullPageOS/nightly/2016-05-27_2016-05-10-fullpageos-jessie-lite-0.6.0.zip.md5

**Comment by icthelp-spje** [comment]
Unfortunately I couldn't wait for the issue to get fixed and just rolled my own solution. Thanks for resolving this though, will keep it in mind for the future. :)

**Comment by guysoft** [comment]
@icthelp-spje sorry about that, you are always welcome to contribute your own solutions here.
