### ISSUE TITLE
update wording on page fro location of fullpageos-network.txt

### ISSUE THREAD

**Issue by biohazd** [guysoft/FullPageOS#170]
Can you update the wording on this line of the main page
"Configure your WiFi by editing fullpageos-network.txt on the root of the flashed card when using it like a flash drive"

Change it to read **"/boot"** and not **"root"**

**Comment by guysoft** [comment]
1. You are welcome to send a pull request
2. The wording is like that because windows users only see the boot
partition and thats why the stuff is all there

**Comment by guysoft** [comment]
Closing if no reply

**Comment by biohazd** [comment]
PR submitted.

**Comment by guysoft** [comment]
@biohazd See point 2. The wording is like that because windows users only see the boot partition and thats why the stuff is all there. Changing it to `/boot` will confuse users.

**Comment by biohazd** [comment]
ahhh, please reject my PR and leave as is :)

**Comment by guysoft** [comment]
Fixed by https://github.com/guysoft/FullPageOS/commit/ff0d6c4cf3f46a85febd2edf07970afc96869347
