### ISSUE TITLE
WiFi connection broken in 0.8.0

### ISSUE THREAD

**Issue by schliflo** [guysoft/FullPageOS#173]
#### What were you doing?

I'm using FullPageOS on a RasPi 3 to power my photobox display (via https://github.com/schliflo/flashair-photobox). Therefore the Pi has to connect to the FlasAir-card's WiFi to display the page. This was working perfectly fine in 0.7.0
WiFi information:
![screenshot_20171017-221127](https://user-images.githubusercontent.com/9881672/31687048-6e045e50-b388-11e7-834a-3e65b4504d41.jpg)

#### What did you expect to happen?

Pi connecting to the specified WiFi

#### What happened instead?

No connection established

#### Was there an error message displayed? What did it say?

Chrome's "there is no connection to the internet connection" page with the dinosaur

#### Version of FullPageOS?

0.7.0 (i double checked this; it's wrong for [0.8.0](https://github.com/guysoft/FullPageOS/blob/0.8.0/src/modules/fullpageos/filesystem/root/etc/fullpageos_version) and [0.8.8](https://github.com/guysoft/FullPageOS/blob/0.8.8/src/modules/fullpageos/filesystem/root/etc/fullpageos_version) - fixed in #172)

**Comment by pspEgg** [comment]
I too have the same exact issue. 

While booting an error message “failed to start secure ssl server” appears as well.

**Comment by petrleocompel** [comment]
I had troubles to connect also. I tried to configure fullpageos-network.txt but then i ended up with `wpa-supplicatn` configuration. And it worked. Give it try.

**Comment by guysoft** [comment]
There is a solution here and no reports if it works. Did anyone test this? Can I close the issue?

**Comment by schliflo** [comment]
As configuration via `fullpageos-network.txt` - like stated in the docs - does not work I would this still consider to be a bug.
I myself downgraded to 0.7 where it does still work. I can test a newer build though if this should be fixed there.

**Comment by guysoft** [comment]
did you try octopi-wpa-supplcant.txt?

**Comment by guysoft** [comment]
Please use ``octopi-wpa-supplcant.txt`` its undocumented because I have no time, it will solve your problem. The file is self explanatory and I am keeping both methods because in some cases only one of the two work.

cc @foosel we should really put ``octopi-wpa-supplcant.txt`` as the default option,

**Comment by marians** [comment]
I got wifi working after filling in my network details in both `fullpageos-network.txt` and `fullpageos-wpa-supplicant.txt`.

**Comment by schliflo** [comment]
I can offer to check this in depth and update the documentation accordingly. But I'm currently really occupied with work so I cannot give an ETA... Will keep you updated.

**Comment by ls009** [comment]
I had the same issues, `octopi-wpa-supplcant.txt` file with the same content as my `fullpageos-wpa-supplicant.txt` fixed the issue

**Comment by guysoft** [comment]
Major changes in 0.9.0 nightly regarding firmware and kernel. Suggest you try now.

**Comment by guysoft** [comment]
Closing if no reply
