### ISSUE TITLE
Resolution modification via config.txt doesn't work

### ISSUE THREAD

**Issue by Fowesed** [guysoft/FullPageOS#192]
I have the same issue like Bolandish posted a couple of weeks ago.

I just installed FullPageOS on a Pi3 and it works fine, but I can't seem to change the output resolution to full HD as the connected display supports it.

I provided the boot/config.txt below.
[config.txt](https://github.com/guysoft/FullPageOS/files/1541914/config.txt)

**Comment by guysoft** [comment]
duplicate pf #190
