### ISSUE TITLE
Unable to connect ot WiFi

### ISSUE THREAD

**Issue by Javelin69** [guysoft/FullPageOS#196]
#### What were you doing?
Setting up FullPageOS over Wifi to display a dashboard.  Modified fullpageos-network.txt as per instructions.

#### What did you expect to happen?
Was hoping the connection would be straright forward.

#### What happened instead?
Unable to establish an Internet connection over WiFi

#### Was there an error message displayed? What did it say?
There is no Internet connection
ERR_INTERNET_DISCONNECTED

#### Version of FullPageOS?
Have tried these 2 versions
2017-10-22_2017-09-07-fullpageos-stretch-lite-0.8.1
2017-10-29_2017-09-07-fullpageos-stretch-lite-0.9.0

I live in Australia and my Raspberry Pi3 Model B is fully updated and upgraded as of 13/01/2018.  
I have followed instructions and suggestions from forums and cannot connect to the internet.

I get no errors while booting.  

All changes made in plain text.

No smart quotes.

Tried 2 different wireless networks.

I am new to Linux so it is possible I have missed something rudimentary.

Your help will be appreciated.

I have tried the following 5 configurations.

-------------------1-------------------------
fullpageos-network.txt - MODIFIED
fullpageos-wpa-supplicant.txt - DEFAULT

## WPA/WPA2 secured
iface wlan0-fullpageos inet manual
    wpa-ssid "MYSSID"
    wpa-psk "MYPASSWORD"

-----------------2------------------
fullpageos-network.txt - DEFAULT
fullpageos-wpa-supplicant.txt - MODIFIED (Left Country as GB)

country=GB
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
  ssid="MYSSID"
  psk="MYPASSWORD"
#}

-----------------3------------------
fullpageos-network.txt - DEFAULT
fullpageos-wpa-supplicant.txt - MODIFIED (Changed Country to AU)

country=AU
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
  ssid="MYSSID"
  psk="MYPASSWORD"
#}

-------------------4-------------------------
fullpageos-network.txt - MODIFIED
fullpageos-wpa-supplicant.txt - MODIFIED (Left Country as GB)

## WPA/WPA2 secured
iface wlan0-fullpageos inet manual
    wpa-ssid "MYSSID"
    wpa-psk "MYPASSWORD"

********************************
country=GB
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
  ssid="MYSSID"
  psk="MYPASSWORD"
#}

-------------------5-------------------------
fullpageos-network.txt - MODIFIED
fullpageos-wpa-supplicant.txt - MODIFIED (Changed Country to AU)

## WPA/WPA2 secured
iface wlan0-fullpageos inet manual
    wpa-ssid "MYSSID"
    wpa-psk "MYPASSWORD"

********************************
country=AU
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
  ssid="MYSSID"
  psk="MYPASSWORD"
#}

Thanks

Geoff

**Comment by Javelin69** [comment]
Meant to mention that I have no issues connecting to either network with Out of Box Raspbian.  Using DHCP.

Regards

Geoff

**Comment by benyanke** [comment]
You seem to have missed uncommenting the #

```
update_config=1

network={
ssid="MYSSID"
psk="MYPASSWORD"
#}
```
should be:
```
update_config=1

network={
ssid="MYSSID"
psk="MYPASSWORD"
}
```

**Comment by Javelin69** [comment]
Thanks heaps works a treat.  I knew it would be something stupid, I just couldn't see it.

**Comment by samscoms** [comment]
It works for me too.
I had to set wifi in both files.

**Comment by guysoft** [comment]
Closing since OP solved issue

**Comment by jyy1082** [comment]
@Javelin69 how about your first configuration?
-------------------1-------------------------
fullpageos-network.txt - MODIFIED
fullpageos-wpa-supplicant.txt - DEFAULT

WPA/WPA2 secured
iface wlan0-fullpageos inet manual
wpa-ssid "MYSSID"
wpa-psk "MYPASSWORD"

I also can not connect wifi by modifying fullpageos-network.txt
