### ISSUE TITLE
Host Name Change

### ISSUE THREAD

**Issue by geocentral** [guysoft/FullPageOS#197]
How do you properly change the host name as I will have multiple devices on the same network?  If I do update the host name will if cause any scripting problems?  

Can it be automated to change the host name on first load?

**Comment by guysoft** [comment]
Like you do in any raspbian/debian based distro:
https://thepihut.com/blogs/raspberry-pi-tutorials/19668676-renaming-your-raspberry-pi-the-hostname

**Comment by guysoft** [comment]
closing if no reply
