### ISSUE TITLE
Chromium auto connect when internet established

### ISSUE THREAD

**Issue by facetime88** [guysoft/FullPageOS#199]
I have setup fullpageos for a kiosk which will load an internet webpage and need to run 24/7 without need human intervention. However, sometime the internet may get down, and the webpage itself may have some javascript that will reload itself, resulting an internet connection error page.

This internet connection error page will stay there forever until I or someone restart the board manually.
Is there any plugin for Chromium, or fullpageos configuration, so whenever an internet connection back established, the page will get reloaded?

Thank you.

**Comment by guysoft** [comment]
You can do the suggestion in this comment:
https://github.com/guysoft/FullPageOS/issues/149#issuecomment-359986758

**Comment by guysoft** [comment]
Closing if no reply
