### ISSUE TITLE
SSID with a space

### ISSUE THREAD

**Issue by FatManLovesPi** [guysoft/FullPageOS#202]
I cannot get this connected to an SSID with a space in the name. I have tried quotes and apostrophe around the SSID name but no luck. 

Any ideas on what I need to do to get this to work?

**Comment by guysoft** [comment]
Please paste your configuration file

**Comment by FatManLovesPi** [comment]
The SSID is "Company WiFi" this is not it but close. It is two works with a one space.

### WIFI CONFIGURATION ######################################################
#The three segments below should cover you in most cases if you run
# a wifi network that uses either WPA/WPA2 or WEP encryption.
#
# Just uncomment the lines prefixed with a single # of the configuration
# that matches your wifi setup and fill in SSID and passphrase.
#
# WPA/WPA2 secured
iface wlan0-fullpageos inet manual
    wpa-ssid Company WiFi
    wpa-psk 112233445566
## WEP secured
#iface wlan0-fullpageos inet manual
#    wireless-essid "put SSID here"
#    wireless-key "put password here"
## Open/unsecured
#iface wlan0-fullpageos inet manual
#    wireless-essid "put SSID here"
#    wireless-mode managed

**Comment by guysoft** [comment]
Did you try using the octopi-wpa-supplicant.txt file? Its the recommended one. Revert your changes in octopi-network.txt and use octopi-wpa-supplicant.txt

**Comment by guysoft** [comment]
closing if no reply.

**Comment by marians** [comment]
@FatManLovesPi Have you tried setting the SSID in quotes?

```
iface wlan0-fullpageos inet manual
  wpa-ssid "Company WiFi"
  wpa-psk 112233445566
```

**Comment by guysoft** [comment]
No reply from OP
