### ISSUE TITLE
After the Page loads i need to press enter 

### ISSUE THREAD

**Issue by Hacket123** [guysoft/FullPageOS#207]
Hi i am trying to use FullPage OS as our Infoscreen. 

My problem, when the age starts i need a 10s later a Enter to start the Infos 

link: http://kulturschuppen.ch/werbung?&fwm[]=1698&fwm[]=1209&fwm[]=1151

any ideas how i can get it ?

**Comment by guysoft** [comment]
You can simulate key presses with xdotool.
Its shipped with FullPageOS, and you can see an example here: https://github.com/guysoft/FullPageOS/blob/devel/src/modules/fullpageos/filesystem/home/pi/scripts/refresh

**Comment by Hacket123** [comment]
Thx ive got it ;)
