### ISSUE TITLE
Xdotool Window ID

### ISSUE THREAD

**Issue by Hacket123** [guysoft/FullPageOS#210]
Hi, 
i am trying to use xdotool to aktivate some keys. 

My Problem: how can i get the Window ID of the Window ?

Any Ideas ?

**Comment by guysoft** [comment]
Check out: https://github.com/guysoft/FullPageOS/blob/devel/src/modules/fullpageos/filesystem/home/pi/scripts/fullscreen
loads it to a variable

**Comment by guysoft** [comment]
Please reply if this solves your issue, otherwise I'll close it.

**Comment by Hacket123** [comment]
thx
