### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ciber96** [guysoft/FullPageOS#212]
#### What were you doing?

Trying to compile the image

#### What did you expect to happen?
No errors on compile
#### What happened instead?
Build Failed
#### Was there an error message displayed? What did it say?
https://pastebin.com/pvdAwmXG
#### Version of FullPageOS?
Latest

#### Screenshot(s) showing the problem:
-

**Comment by guysoft** [comment]
Fixed, please pull changes from CustomPiOS

**Comment by guysoft** [comment]
Still fails, I need to remove
``unpack /filesystem/home/root /root root`` 
When next to computer

**Comment by marians** [comment]
@guysoft Where is that? I can't find it in FullPageOS. Is it in CustomPiOS?
