### ISSUE TITLE
Future Request: auto VPN connection

### ISSUE THREAD

**Issue by pompushko** [guysoft/FullPageOS#218]
Hello guysoft!

Could you add txt configuration file in root for automatic VPN connection? Like with webpages?

**Comment by guysoft** [comment]
You are welcome to implement it yourself, I accept pull requests..
Moreover I have no VPN connection to test against. You could write a guide for a start, then its easy to add a CustomPiOS module.

**Comment by pompushko** [comment]
Hello Guy! Could you explain more about CustomPiOS module?19.03.2018, 12:51, "Guy Sheffer" <notifications@github.com>:You are welcome to implement it yourself, I accept pull requests..
Moreover I have no VPN connection to test against. You could write a guide for a start, then its easy to add a CustomPiOS module.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- С уважением,Артём Рощеня+375(44)772-00-70

**Comment by guysoft** [comment]
See: https://github.com/guysoft/CustomPiOS/wiki/Modules
Again, I suggest you first find a guide that works for you, then you can turn it in to a module.

**Comment by pide2000** [comment]
I wrote a description how to switch on vpn and autostart it. Just follow the instructions here https://github.com/guysoft/FullPageOS/issues/187 
It should be easy to put this into a module.

**Comment by guysoft** [comment]
You are welcome to implement it yourself, I accept pull requests
I have no time to add these features. Nor time to test them, I manage 5 other distros. You are welcome to send a pull request.

**Comment by guysoft** [comment]
Closing if no reply

**Comment by pide2000** [comment]
Yeah, close it. At the moment I have no time to implement it. If it is implemented in future we can reference to this issue anyway.

**Comment by pompushko** [comment]
bad. very bad :(

**Comment by guysoft** [comment]
@pompushko You are welcome to implement it, I have no time, no money and I am doing this for free. I am not working for you.

**Comment by pompushko** [comment]
i could make donation :D
