### ISSUE TITLE
Graphics acceleration?

### ISSUE THREAD

**Issue by m2pc** [guysoft/FullPageOS#22]
Hi, I'm curious if your OS supports any sort of graphics acceleration on the Pi? I recall trying to use Chromium on an older Pi and it was painfully slow to work with.  I also seem to remember some developers were working on a more modern X server that supported some of the acceleration available in the Pi's GPU or something similar.

Thanks and I'm excited to try your OS on some projects!

**Comment by guysoft** [comment]
Indeed, its a pain. I know that the Pi3 has experimental acceleration stuff, but I didn't get time to understand how to implement it. See ``optional experimental GL desktop driver (can be enabled using advanced options in command-line raspi-config)`` mention in [raspbian release notes](http://downloads.raspberrypi.org/raspbian/release_notes.txt).
If anyone wants to test and report, I can add this.

**Comment by heibor** [comment]
Improved performance is always exciting.

**Comment by guysoft** [comment]
In RC1
