### ISSUE TITLE
License

### ISSUE THREAD

**Issue by philipkiely** [guysoft/FullPageOS#224]
What license is FullPageOS offered under? There is no license.txt in the repo.

**Comment by guysoft** [comment]
Wha, not sure how that got under the radar. GPLv3, like all my distros.

**Comment by guysoft** [comment]
Fixed by https://github.com/guysoft/FullPageOS/commit/ab4c006ba5d520dfd9c75b4a6f4ee5bccc03054f

**Comment by guysoft** [comment]
Are you planing to use it with GrammieGram?

**Comment by philipkiely** [comment]
Yes I was hoping to. It's my first time trying to make a consumer product so any code I don't have to write is a plus.

**Comment by guysoft** [comment]
Cool, message if you need anything on the CustomPiOS/FullPageOS side

**Comment by philipkiely** [comment]
Awesome, thanks!
