### ISSUE TITLE
Only displays placeholder page

### ISSUE THREAD

**Issue by cryptadd** [guysoft/FullPageOS#225]
#### What were you doing?
Loaded image onto sd card linked the pi directly to my pc my websites loaded and everything is good. 
The only issue is that it says placeholder page on the login page. 

Is there a fix for this?

https://gyazo.com/281311734deec594ac82e491fc43ce8c

v0.8.1

**Comment by guysoft** [comment]
This means you flashed the image wrong, you are not supposed to see that but a diffrent web page on boot.
1. check your SD card is not corrupted
2. Try version 0.9.0 for a lack of a better thing to look for

**Comment by guysoft** [comment]
Closging if no reply
