### ISSUE TITLE
Blank Pages

### ISSUE THREAD

**Issue by gleneatkinson** [guysoft/FullPageOS#227]
#### What were you doing?

trying to load any external address either with url or ip address
#### What did you expect to happen?
Page would open and display

#### What happened instead?
a blank white page would display

#### Was there an error message displayed? What did it say?
no errors

#### Version of FullPageOS?
0.8.1 and 0.9.0

[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:
![image](https://user-images.githubusercontent.com/4526511/39414114-5bd1dc48-4c77-11e8-89e4-ff9555911fcc.png)

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by gleneatkinson** [comment]
Please note this only occurs in full page dash board if I don't use the dashboard a page will load fine

**Comment by guysoft** [comment]
FullPageDashboard board is dead an unsupported, its only there because no one would support it or write anything better (which should be really easy considering that https is not working).

If it does not do what you want don't use it.
