### ISSUE TITLE
Exit Chromium

### ISSUE THREAD

**Issue by TimDowker** [guysoft/FullPageOS#23]
Is there a way to exit chromium once booting has completed?  I need to troubleshoot some networking issues and can't get back to the command line locally.

**Comment by guysoft** [comment]
Good point,
1. You can run from tty (you enter tty1 by pressing doing ``ctrl+alt+F1`` ) ``DISPLAY=:0 xterm``
2. or you can just use the tty terminal there.
That should give you a terminal, exiting chromium usually results in a of restart of ``lightdm``, this is so it will keep running in case chromium crashed.
4. If you have a serial connection device you can use that too, [more information here](http://elinux.org/RPi_Serial_Connection)

If you need any other way to enter a terminal please share :)

**Comment by guysoft** [comment]
Closing if no reply

**Comment by guysoft** [comment]
Thanks for cleaning up :)
