### ISSUE TITLE
Touchscreen Issue with new Pi3 B+

### ISSUE THREAD

**Issue by conrad9900** [guysoft/FullPageOS#230]
#### What were you doing?

Setting up a pi3 B+ with an official 7inch Touchscreen

#### What did you expect to happen?

The touch input to be normal. It works perfect with the pi3 B with no calibration required

#### What happened instead?
The calibration is not accurate as you move around the screen.Please see video attached

#### Was there an error message displayed? What did it say?

No error message

#### Version of FullPageOS?

2018-03-13-fullpageos-stretch-lite-0.9.0

#### Screenshot(s) showing the problem
:
https://drive.google.com/open?id=0B_viKi-80bqNXzcweXVVVjFpajA

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment]
Make sure you didn't enable overscan:
https://lb.raspberrypi.org/forums/viewtopic.php?p=821754&sid=4c08c2ff76c96d9267a76ad8b6a074e7#p821754
Beyond that this is not a FullPageOS issue, its a rapsbian issue.

**Comment by guysoft** [comment]
Closing if no reply
