### ISSUE TITLE
Set up with static IP on eth on boot

### ISSUE THREAD

**Issue by charliwest** [guysoft/FullPageOS#231]
#### What were you doing?
I would like to be able to boot first time to a WIRED connection with a static IP

I think this option used to be in fullpageos-network.txt but with wpa changes it is no longer an option.
#### Version of FullPageOS?
 0.9.0

**Comment by guysoft** [comment]
Duplicate of #222

**Comment by charliwest** [comment]
That other issue is about WiFi isn’t it? I am asking about eth0/wired connection

**Comment by guysoft** [comment]
Ok, see https://github.com/guysoft/OctoPi/issues/202 
I can't really do anything beyond that. Its part of Raspbian.

**Comment by IT-Mase** [comment]
Hi !
I had the same issue ...
Found an answer, for last version which is under raspbian bookworm [here](https://www.abelectronics.co.uk/kb/article/31/set-a-static-ip-address-on-raspberry-pi-os-bookworm) !
It worked like a charm for me !

Ciao !
