### ISSUE TITLE
Pi 3B+ with FullPageOS 0.9.0 (2018-04-22) does not boot.

### ISSUE THREAD

**Issue by davidus-sk** [guysoft/FullPageOS#232]
#### What were you doing?
I have a brand new (box of them actually) RPi 3B+ with 8GB Sandisk SD card. I imaged the SD card and tried to boot the RPi 3B+ up.

#### What did you expect to happen?
The RPi should boot into the OS.

#### What happened instead?
Nothing. The screen is dark (unable to detect HDMI signal I suppose), the red LED goes in and out while the green LED appears to show OS booting (it flickers). I have tried to boost the HDMI signal with the same exact result. The red LED is sporadic, it goes off, then it comes back on, then it appears to blink in intervals, then it goes off again. I have never seen this before.

I realize that the red LED signals power issues, but I have tried about half a dozen power supplies and I get the same problem with every one of them. When I put the same exact SD card into RPi 3Bv1.2 it works just fine with the same set of power supplies. Thus at least in my head I have eliminated the card and power supply as the problem. I have also tried several other 3B+ RPis and the result is identical. But like I said, it does boot just fine with RPi 3Bv1.2.

Update: I took stock RASPBIAN STRETCH LITE (2018-04-18) image and the RPI 3B+ boots just fine. So it is definitely FullPageOS 0.9.0 issue.

#### Was there an error message displayed? What did it say?
No message is show. 

#### Version of FullPageOS?
0.9.0 - latest stable downloaded from the mirror today.

**Comment by davidus-sk** [comment]
@guysoft It is 2A but see my update above. I flashed the SD card with the stock Stretch Lite image and it boots just fine with the same exact power supply and the same exact RPi 3B+. However the RPi 3B+ won't boot with the FullPageOS image. Thus through the process of elimination I believe there is something wrong the the image.

**Comment by guysoft** [comment]
Multiple users, including myself,  have tested 0.9.0 and ir worked, so I am bot sure what you can do. Have you tried disabling the GPU acceleration on FullPageOS using your 3B? that's the only thing different from plain Raspbian on boot.

**Comment by davidus-sk** [comment]
@guysoft I am still trying to get it to work, I will be posting my updates here. I took a fresh SD card, flashed it with 0.9.0 and retried. Here is what I am seeing: The system boots up (yay), it resizes the file system and reboots. It doesn't come back from the reboot. It seems to be stuck in cycle where I can see the monitor is about to get some signal as it flickers and the green LED flickers as well and then it goes dark. Rinse and repeat. So the resize does something that damages the OS on the card itself?

**Comment by guysoft** [comment]
I don't know, the resize is purely done by raapbian. The only thing that might be different is the GPU is enabled by default

**Comment by davidus-sk** [comment]
@guysoft can you please tell me which parameter disables the GPU? I googled it and it seems the OS needs to boot to do that. Can I do it pre-boot in one of the config TXT files?

BTW I have tried about 7 different SDs with the same result. Post FS resize the system fails to boot up.

**Comment by guysoft** [comment]
GPU is enabled on the first boot by running a script at ``/home/pi/scripts/enable_gpu``.
You can empty the content of that file before first boot, then it should not get enabled.

**Comment by davidus-sk** [comment]
@guysoft I disabled GPU by reversing what was done in the enable_gpu script and it boots up now. I have few questions though:

**Comment by guysoft** [comment]
It works, I have no idea why the RaspberryPi foundation disables it by default. The only guess I have is that not all Pis are the same and that it works only in some of them. But I have none to test against. You can try report to the raspberrypi kernel team that your GPU does not work on that particular pi and see if they have anything to say.

**Comment by davidus-sk** [comment]
Thanks for your response today @guysoft

**Comment by aijazzz** [comment]
Hi, I am facing exactly the same problem and rp3b+ wont show anything. How do you edit the image to remove that script so that it wont run? Can anyone please help? thanks.

**Comment by guysoft** [comment]
@aijazzz You need a inux machine, that can mount an ext4 filesystem (for example a raspberrypi running raspbian).

Have you tried booting normal raspbian first and see if that works?

**Comment by aijazzz** [comment]
Thanks @guysoft, I did  exactly that by booting it using an old rp3b and removing enable_gpu script after which it is working fine in rp3b+. 
Now my problem is that I want to modify the original image to not include that script so that I can give it to someone else who may not be familiar with linux. I assume that I have to build it myself using source from github. Do I understand it correctly that it is not a problem with all rp3b+ and that is why you cannot fix/remove that enable_gpu script for + model? Thanks for your support :)

**Comment by guysoft** [comment]
You can use [CustomPiOS](https://github.com/guysoft/CustomPiOS) which is used to build FullPageOS.
Look at the source code at this repository.
