### ISSUE TITLE
[Question] Accessing Chromium console?

### ISSUE THREAD

**Issue by shaunhurley** [guysoft/FullPageOS#240]
Is it possible to open the Chromium console in fullpageos?  I don't seem to be able to directly from the browser, assuming it has been disabled?  Is there a configuration option that would allow it to be opened?

I'm using full page in a kiosk setting, occasionally see issues with the web page that I only see on the pi, and would like to look at the  console for error / debug messages, etc.

Thanks!

**Comment by guysoft** [comment]
ctl+t will open a new tab with all browser controls
