### ISSUE TITLE
RAM Full?

### ISSUE THREAD

**Issue by a2th3g** [guysoft/FullPageOS#244]
#### What were you doing?
Running multiple setups with a touchscreen, and all start behaving  **extremely** slow after about 15 hrs of use.

#### What did you expect to happen?
Need stable runtime, or auto restart at pre determined times
#### Was there an error message displayed? What did it say?
no errors just slow performance
#### Version of FullPageOS?
Running for about a month....not sure version.
[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment]
1. Please provide the version, you message include the instructions how.
2. what page are you running?

**Comment by a2th3g** [comment]
The site is “Monday.com”

Linux fullpageos 4.14.34-v7+ #1110 SMP

My goal at the moment is force a reboot based on time. And update the load/splash screen.

**Comment by guysoft** [comment]
Can you please answer my questions, I can't help you otherwise.
You did not answer:
1. Please provide the version (of FullPageOS), you message include the instructions how.
3. Additionally want version of RaspberryPi are you using?

**Comment by guysoft** [comment]
Closing if no reply
