### ISSUE TITLE
Increase Font Size or Zoom Level?

### ISSUE THREAD

**Issue by jarrah31** [guysoft/FullPageOS#249]
Is it possible to increase the font size or zoom level within FullPageOS please?

I'm using it to display Home Assistant on a Hyperpixel 4 display, but the text size is very small. I've been googling for a solution but not found any yet so hoping someone on here may know the answer.

Thanks.

**Comment by guysoft** [comment]
Yes you can. [See here](https://superuser.comhttps://superuser.com/a/1222862/268425). You can add arguments to [/home/pi/scripts/start_chromium_browser](https://github.com/guysoft/FullPageOS/blob/devel/src/modules/fullpageos/filesystem/home/pi/scripts/start_chromium_browser)

**Comment by jarrah31** [comment]
Thank you, that works great!
