### ISSUE TITLE
[feature request] Append serial number and or other things

### ISSUE THREAD

**Issue by xvilo** [guysoft/FullPageOS#251]
It's not a bug, but a feature request. 
It would be great if the contents of fullpageos.txt (the url) would be parsed with some dynamic data such as it's serial number. 

for example, we could set it to something like this:
```txt
https://domain.com/?screenid={serial}
```

That would resolve to:
```txt
https://domain.com/?screenid=123456780
```

The reason for this is that we can easily detect which pi it is going to our webpage and serve diffrent content.

**Comment by guysoft** [comment]
You are welcome to send a pull request.

**Comment by xvilo** [comment]
Done.
https://github.com/guysoft/FullPageOS/pull/252

**Comment by guysoft** [comment]
Awesome, merged.
