### ISSUE TITLE
Proxy 

### ISSUE THREAD

**Issue by dkj82** [guysoft/FullPageOS#255]
#### What were you doing?

[Please be as specific as possible here]

#### Version of FullPageOS?

[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]
how to add proxy? where? help

**Comment by guysoft** [comment]
http://lmgtfy.com/?q=how+to+set+up+proxy+chromium

Attitude improves when you fill in the template.  Its there for you.

**Comment by guysoft** [comment]
No reply, closing
