### ISSUE TITLE
Link to local HTML

### ISSUE THREAD

**Issue by mariomuellergermany** [guysoft/FullPageOS#257]
#### What were you doing?

I want to open a html-file located on the SD

#### What did you expect to happen?
open the local html

#### What happened instead?

file not found or 404 error

#### Was there an error message displayed? What did it say?
see above

#### Version of FullPageOS?

2018-09-13_2018-06-27-fullpageos-stretch-lite-0.10.0

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

You wrote in 

https://github.com/guysoft/FullPageOS/issues/33

> Beyond that, I think you should SSH into the the Pi and upload files to a folder under webroot, then reference them as http://localhost/folder/filename.html.
> webroot is located at /var/www/html
> 

As I am new to linux: I cannot find the var folder

I attached a screenshot
![unbenannt](https://user-images.githubusercontent.com/44089800/46867805-be787300-ce15-11e8-838d-c49384d67365.JPG)

Were there any significant changes since the above mentioned issue?
I will be glad receiving an answer.

Regards Mario

**Comment by guysoft** [comment]
the var folder is in the second partition which is ext4 format and not visible in windows.  Closing since this is not a FullPageOS issue.
