### ISSUE TITLE
Htaccess css problem

### ISSUE THREAD

**Issue by dagerud** [guysoft/FullPageOS#261]
#### What were you doing?
An infosign that login to a site with htaccess as an example: HTTP://test:password@testsite.xyz/test/index.php

#### What did you expect to happen?
It should login to my site and show my info.

#### What happened instead?
It showed info, but without css scheme. It does not load images and such content.
#### Version of FullPageOS?

0.9.0

#### Screenshot(s) showing the problem:

sensitive information on site.

**Comment by guysoft** [comment]
Closing of no reply
