### ISSUE TITLE
Rainbow Square

### ISSUE THREAD

**Issue by jacobgraf** [guysoft/FullPageOS#27]
I have a brand new Raspberry Pi 3. I images my SD card using v.5 and modified the wifi config and start URL but when I boot it up, all I get is a rainbow square. This was a CanaKit which is using a 2.5A power supply so I know it has access to enough power. Any other ideas what might be going on here?

**Comment by guysoft** [comment]
Please use version 0.6.0 RC.
0.5.0 was released before RaspberryPi 3 existed and therefore does not
support it.

**Comment by jacobgraf** [comment]
That worked! I didn't see this in the documentation anywhere. Thanks!
