### ISSUE TITLE
Add bookmark to chromium browser from command line

### ISSUE THREAD

**Issue by jfcaldeira** [guysoft/FullPageOS#277]
I have changed fullscreen file to display without full screen and the start_chromium_browser without kiosk and to start with 2 tabs opened in specific urls.

I would like to know if it's possible to set a configuration to automatically have bookmark tab open and add bookmarks to it through command line?

**Comment by guysoft** [comment]
Thats a chromium issue, not a FullPageOS issue. Since you are using chromium in a way not supported or shipped here.

You can ask at the chromium discussion groups at: https://www.chromium.org/developers/discussion-groups
