### ISSUE TITLE
Start of OS gets stuck and only says "crng init done"

### ISSUE THREAD

**Issue by dmartzol** [guysoft/FullPageOS#278]
#### What were you doing?
Starting FullpageOS for the first time. I tried with both WIFI and Ethernet. Connected over HDMI to a screen.

#### What did you expect to happen?
Start the OS normally and either system prompt or X UI appear.

#### What happened instead?
Sistem got stuck in some step and showing only "crng init done".

#### Was there an error message displayed? What did it say?
No error message. Just "crng init done"

#### Version of FullPageOS?
Can't access /etc/fullpageos_version, but name of image file is 2018-04-22_2018-04-18-fullpageos-stretch-lite-0.9.0, so I guess is version 0.9.0

**Comment by dmartzol** [comment]
Just read in the README it is supposed to not work with RPi 2 or later. I can't delete this issue

**Comment by dmartzol** [comment]
Ok, so the Rpi is version 2 I believe. It is only the PCB that is revision 1.2. So this OS is still supposed to work with my RPi.

**Comment by guysoft** [comment]
Can you try the latest RC3, non-acceleration version?
Rpi 2 should work fine.

**Comment by guysoft** [comment]
Can you try the latest RC3 0.10.0, non-acceleration version?
Rpi 2 should work fine.

**Comment by dmartzol** [comment]
Thanks @guysoft ! It works downloading the version you specified. The first time I went to the official mirror and downloaded the version showed in the first folder. I wasn't clear to me I had to find a different version.
