### ISSUE TITLE
multiple pages/tabs dont open 

### ISSUE THREAD

**Issue by gbrakcounty** [guysoft/FullPageOS#280]
#### What were you doing?
trying to open multiple webpages specified in /boot/fullpageos.txt as http://site1.com && http://site2.com.  Also tried using "&" instead of "&&".  I tried using the FullPageDashboard but the 2nd tab either never loads or loads after a very long time.  Checked my network settings they're fine.
[Please be as specific as possible here]

#### What did you expect to happen?
multiple webpages would load
#### What happened instead?
only the first webpage loaded
#### Was there an error message displayed? What did it say?
none
#### Version of FullPageOS?
not available in the location listed below.
[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment]
That is impossible, because a webbrwoser only lets you see one page at a time. To solve this FullPageOS is shipped with an app called FullPage Dashboard as the default. You need to use ``/boot/fullpagedashboard.txt`` with newline for each new page. Also it will only use that file in the first boot.
Alternatively you can use the GUI that is part of FullPageDashboard.

**Comment by gbrakcounty** [comment]
It's possible. I actually have an img I created of fullpageos that opens multiple pages but I had other problems with it that's why I can't use it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by guysoft** [comment]
I don't understand what you mean by "an img you created with multiple pages". Did you use FullPageDashboard for that? Or did you generate your own image?

**Comment by gbrakcounty** [comment]
Sorry I meant image but used the file extension.img

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
