### ISSUE TITLE
How to reload if Page isnt loaded correctly?

### ISSUE THREAD

**Issue by mkkagain** [guysoft/FullPageOS#282]
My Webpage reloads itself every 60 seconds.

Sometimes an error occured and the "Oh no!" Screen from Chrome is beeing showed.

Is it possible to check, whether this error happens and hard reload the page? Or restart the Pi?

**Comment by guysoft** [comment]
Take a look at this:
https://github.com/guysoft/FullPageOS/blob/devel/src/modules/fullpageos/filesystem/home/pi/scripts/start_chromium_browser#L9

If you edit ``/home/pi/scripts/start_chromium_browser`` you can create this behaviour.

Documentation pull requests are welcome.
