### ISSUE TITLE
unable to rotate hdmi display

### ISSUE THREAD

**Issue by gbrakcounty** [guysoft/FullPageOS#289]
Not sure if this is specific to fullpageos or not, but since its a custom os and something standard to raspbian isnt working, i figured id post here.  display_rotate and display_hdmi_rotate do not work at all in /boot/config.txt.  I am trying to use it for a digital ticket counter display and the client wants the tv in portrait mode.  the tv is old and does not have a rotate function.  any suggestions?

**Comment by guysoft** [comment]
How did you solve your issue?

**Comment by gbrakcounty** [comment]
“display_hdmi_rotate=3” in /boot/config.txt works only if the GL driver is disabled in raspi-config.

**Comment by guysoft** [comment]
Yes, that is not implemented by the driver, 
Related to: https://github.com/guysoft/FullPageOS/issues/137

**Comment by thfrei** [comment]
I updated the FAQ: https://github.com/guysoft/FullPageOS/wiki/FAQ#how-to-rotate-the-screen-to-a-vertical-position, please also see: #421
