### ISSUE TITLE
Black screen on pi3 model À+

### ISSUE THREAD

**Issue by Glujaz** [guysoft/FullPageOS#290]
#### What were you doing?

Booting the OS after creating the SD card. At first boot it was ok. I had a settings page somehow. After that, nothing. There is no cursor or anything appearing, and the model A has no Ethernet, so no SSH.

#### What did you expect to happen?

See at least the full page dashboard appear.

#### What happened instead?

Black screen appears, but nothing else, and nothing is happening on the SD card
#### Was there an error message displayed? What did it say?
Nothing
#### Version of FullPageOS?

The last normal one (as of 1 August). Can't get access to the file as no keyboard or ssh available...

Thanks in advance for your help.

**Comment by Glujaz** [comment]
Ok, was my monitor. I use an Apple Cinema Display HD, which is very picky with input type... It works fine with raspian, but not with FullPageOS though...

Now is connecting to WiFi... and while I set everything right, it's not working...

**Comment by guysoft** [comment]
Did you solve your issue in the end?

**Comment by Glujaz** [comment]
Yes I did. Though, the raspi 3 A+ is slow...
Sorry to say, but after tweaking a little bit with FullpageOS, not having auto refresh is very limiting...

Sorry for the opened issue.

Von meinem iPhone gesendet

Am 01.08.2019 um 19:11 schrieb Guy Sheffer <notifications@github.com>:

﻿Did you solve your issue in the end?
