### ISSUE TITLE
How to enable a DNS server in the network

### ISSUE THREAD

**Issue by dakoller** [guysoft/FullPageOS#3]
...wanted to know a way on how to define a dns server.

**Comment by guysoft** [comment]
The same way you would define it on any installation of Rapsbian.
You can follow this guide: 
http://theurbanpenguin.com/wp/index.php/raspberry-pi-setting-a-static-ip-address/

**Comment by dakoller** [comment]
THX!

Guy Sheffer <notifications@github.com> schrieb am Di., 20. Okt. 2015, 17:10:
