### ISSUE TITLE
Shutdown on boot

### ISSUE THREAD

**Issue by SloCompTech** [guysoft/FullPageOS#304]
#### What were you doing?
Installed fresh FullPageOS version 0.10.0. Raspberry (3B+) booted first time. When booted it automatically shutted down. Now it doesn't boot again.

#### What did you expect to happen?
Boot normally and open web page.

#### What happened instead?
Raspberry Pi shuts down.

#### Was there an error message displayed? What did it say?

Just showing Started ...
Then just starts showing Stopped ...

#### Version of FullPageOS?
0.10.0

**Comment by guysoft** [comment]
Can you try replashing? I am not sure if the image was flashed correctly to start with.

**Comment by SloCompTech** [comment]
I will try again, and report.

**Comment by guysoft** [comment]
Any news?

**Comment by SloCompTech** [comment]
Tried again:
- Downloaded version 0.10.0 again
- Written image with balena etcher to SD card
- booted up Raspberry Pi 2B+
- it booted up, but just after booting up, it shuted down automatically
![IMG_20191211_194901](https://user-images.githubusercontent.com/11356157/70650854-24e26680-1c50-11ea-95ce-b75df91a8fa9.jpg)

**Comment by guysoft** [comment]
That screenshot is unhelpful, it just shows a showdown process.
There is something triggering a shutdown - if you just flash plain Raspebian does this happen too?

**Comment by SloCompTech** [comment]
No if I flash normal raspebian it works

**Comment by guysoft** [comment]
Ok, can you provide a fuller boot log in any way? I really can't tell what is going on.
I am just not sure how to debug this? Perhaps a video of the whole boot sequence?

**Comment by SloCompTech** [comment]
Hi,
sorry it is model 2B, here is `/var/log/syslog` https://pastebin.com/0ig0tc5q

**Comment by guysoft** [comment]
Might be this error:
```
Dec 11 18:50:36 fullpageos lightdm[448]: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
```

What is in ``/etc/lightdm/lightdm.conf``?

Also, did you try 0.11.0 RC1? might be solved there. it looks like lightdm is having issues.

**Comment by SloCompTech** [comment]
Hi,
just tried 0.11.0, no luck, still no audio output.

**Comment by guysoft** [comment]
@SloCompTech You didn't mention anything about audio output until now, in fact, this makes no sense because you said in the issue that the gui shuts down right away - have you solved it? If not, how are you testing the audio?

**Comment by SloCompTech** [comment]
Ouch, to much stuff in my head. I meant video output after boot. RPi boots up then there is no video signal on HDMI (monitor does not detect signal).

**Comment by guysoft** [comment]
@SloCompTech but you posted the screen here: https://github.com/guysoft/FullPageOS/issues/304#issuecomment-564683131

Did you switch hardware?  Is the system working with other monitors?

**Comment by SloCompTech** [comment]
I will try that.

**Comment by SloCompTech** [comment]
Now working with RPi2B with version 0.11.0 build 26/9/2019.

**Comment by guysoft** [comment]
@SloCompTech Did you do anything to fix it? Or just reflashed?

**Comment by SloCompTech** [comment]
Just flashed version 0.11.0, nothing modified.
