### ISSUE TITLE
Can't hide mouse coursor

### ISSUE THREAD

**Issue by Szwajowy** [guysoft/FullPageOS#306]
#### What were you doing?
I followed this steps:

> edit lightdm.conf found in /etc/lightdm/lightdm.conf and look for
> 
> #xserver-command=X
> change that to
> 
> xserver-command=X -nocursor
> reboot and cursor should not appear

#### What did you expect to happen?
cursor should not appear

#### What happened instead?
cursor appeard

#### Was there an error message displayed? What did it say?
no errors

#### Version of FullPageOS?

2019-09-26-fullpageos-no-acceleration-buster-lite-0.11.0

**Comment by guysoft** [comment]
Hey,
I am not sure how to fix that on FullPageOS side, seems like a lightdm bug, you shoud file it at https://launchpad.net/lightdm

**Comment by Szwajowy** [comment]
I found solution !
You need to edit this file:
/usr/share/lightdm/lightdm.conf.d/*.conf
instead of one mentioned in wiki.

**Comment by guysoft** [comment]
If there is a way to make it hide when its not moving I'd add that to the distro

**Comment by Szwajowy** [comment]
I'm not asking you to change it on dostęp, but to change it on the Wiki section.

**Comment by guysoft** [comment]
@Szwajowy Oh, that was donated, you can add it there yourself, its a wiki :)

If you are having issues you can tell me exactly what to change and I can edit it.

**Comment by Szwajowy** [comment]
Ohh, okay. 
Thanks for help :)
