### ISSUE TITLE
Pass Arguments to Chromium upon startup

### ISSUE THREAD

**Issue by tmello01** [guysoft/FullPageOS#314]
Is there a way to pass arguments to the chromium application before it starts up? For example, I need the browser to be run in kiosk mode, with disabled pinch-to-zoom, and disabled over-scroll history change. These can all be disabled by passing various arguments to the chromium-browser when it starts up, is there a way I can configure these parameters?

**Comment by guysoft** [comment]
Three of those settings are the default set in the distro 
https://github.com/guysoft/FullPageOS/blob/devel/src/modules/fullpageos/filesystem/home/pi/scripts/start_chromium_browser#L11
You can edit the script to add more or remove settings. 
When you say "configure them as parameters?" Where would you actually configure them?

**Comment by stappersg** [comment]
@tmello01 see #316 and please consider closing this issue.

**Comment by guysoft** [comment]
Closing due to no reply.
Since an answer was given on Jan
