### ISSUE TITLE
Chromium Update notification

### ISSUE THREAD

**Issue by DL6JJ** [guysoft/FullPageOS#319]
#### Chromium Update notification
Chromium shows an unexpected notification. It persists even, when it was updated manualy. According to the chromium docs, this behavior should not occur under Linux.

Some ideas?

It is really frustrating, because it occurs seemingly random across devices.

### Looks like this: 
![image_2020-02-17_10-37-44](https://user-images.githubusercontent.com/24417737/74641680-fa41ec00-5171-11ea-9da1-e8852f544ca2.png)

(The text says: Chromium couldn't update to the latest version, so you're missing out on new features and security fixes.)

**Comment by guysoft** [comment]
Has been fixed in #317 pull request.
You can fix the workaround by adding ``--disable-component-update`` in the startup command. There is a new nightly coming out with this fix.

**Comment by mschmidt291** [comment]
Actually strange. disable-component-update is not always disabling this message - don't know why.
`--simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'` does the trick and fixed it for us! :)
@DL6JJ

**Comment by Dragon0501** [comment]
Where does this lines have to be added?

**Comment by DL6JJ** [comment]
`/home/pi/scripts/start_chromium_browser` in line 6 or 11. Depends which case you use.

You can find the original file [here](https://github.com/guysoft/FullPageOS/blob/devel/src/modules/fullpageos/filesystem/home/pi/scripts/start_chromium_browser)

@Dragon0501

**Comment by Dragon0501** [comment]
Thank you very much

**Comment by guysoft** [comment]
I am closing this since it has been fixed and should be available in the current nightly.
