### ISSUE TITLE
Add minimum size of the SD-card to requirements

### ISSUE THREAD

**Issue by stappersg** [guysoft/FullPageOS#328]
#### What were you doing?

Reading the README.md   as preparation for actual using `FullPageOS`.

#### What did you expect to happen?

That the _requirements_ state the minimum SD-cards size.

#### What happened instead?

Did not find that data, created this  issue.  `8^)`

**Comment by guysoft** [comment]
4GB. Class 10 and above.
The image size is just a little over 3GB

**Comment by guysoft** [comment]
PR is welcome

**Comment by stappersg** [comment]
Merge request #329 is accepted, so now closing this issue.
