### ISSUE TITLE
Touch Controls are inverted on x axis

### ISSUE THREAD

**Issue by conrad9900** [guysoft/FullPageOS#338]
#### What were you doing?

Booting to a HDMI touchscreen

#### What did you expect to happen?

Normal touchscreen actions

#### What happened instead?

up and down touch is ok, left and right is inverted

#### Was there an error message displayed? What did it say?

No error messages

#### Version of FullPageOS?

2019-12-01_2019-09-26-fullpageos-buster-lite-0.11.0
--
[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment]
What type of touchscreen?

**Comment by guysoft** [comment]
Any news on this? Is this the official touchscreen or something else?

**Comment by conrad9900** [comment]
> Any news on this? Is this the official touchscreen or something else?

No, it is not official. It is a 15" POS, uses eGalax Driver.
I have tested several settings and i have concluded that the chinese screen just isnt worth the hassle.
This isssue can be closed
