### ISSUE TITLE
http://unofficialpi.org/ is down

### ISSUE THREAD

**Issue by SchIiIZzZOoO** [guysoft/FullPageOS#341]
do you have a different download-Link?
http://unofficialpi.org/Distros/FullPageOS/2019-12-01_2019-09-26-fullpageos-buster-lite-0.11.0.zip does not work...

**Comment by guysoft** [comment]
Thanks for alerting, investigating, the domain has been donated for the project, checking with the owner

**Comment by guysoft** [comment]
Fixed
