### ISSUE TITLE
https://bit.ly/fpossetup

### ISSUE THREAD

**Issue by pthoelken** [guysoft/FullPageOS#347]
http://bit.ly/fpossetup and https://bit.ly/fpossetup is not reachable.

**Comment by guysoft** [comment]
@tailorvj

**Comment by guysoft** [comment]
The guy who hosted it closed the hosting account. I am trying to find solutions. I have where to host it elsewhere, but it would take a while to figure out how to get the original text and page.

**Comment by pthoelken** [comment]
Do you need a domain and hosting? I can support you with my company.

**Comment by tailorvj** [comment]
The website is online. The link you referenced is simply wrong. The actual
link is http://bit.ly/FPOSSETUP

**Comment by guysoft** [comment]
URL is written wrong, its at: http://bit.ly/FPOSSETUP
