### ISSUE TITLE
setup manual date and time on boot

### ISSUE THREAD

**Issue by 4o4forbidden** [guysoft/FullPageOS#351]
Hello everyone, im facing a problem with the dist where im trying to manually setup the date & time while booting via running these commands 

timedatectl set-ntp 0
read -p myDate
timedatectl set-time myDate

but till now i can't find where to put them i successfully achieved showing a message via an "echo" in rc.local file when booting but command read -p is jumped and directly showing chromium 

any help ? 

i'm using the last official build of FullPageOS
2019-12-01_2019-09-26-fullpageos-buster-lite-0.11.0.zip

Thanks

**Comment by guysoft** [comment]
This is how it is done in the build script: 
```
ln -fs /usr/share/zoneinfo/"$FULLPAGEOS_OVERRIDE_TIMEZONE" /etc/localtime
    dpkg-reconfigure -f noninteractive tzdata
```
source:  https://github.com/guysoft/FullPageOS/blob/devel/src/modules/fullpageos/start_chroot_script#L76
