### ISSUE TITLE
force always boot on HDMI

### ISSUE THREAD

**Issue by 4o4forbidden** [guysoft/FullPageOS#353]
Hello, i wonder how can i force the os to use HDMI because if the pi has started before the TV, it wont recognise the HDMI unless i reboot the pi with the TV on and waiting for a signal ! 

thanks.

**Comment by 4o4forbidden** [comment]
no answers ?

**Comment by guysoft** [comment]
``hdmi_force_hotplug=1``
its in the official raspberrypi documentation and I just googled "hdmi raspberrypi force" to get it
https://www.raspberrypi.org/documentation/configuration/config-txt/video.md
