### ISSUE TITLE
Read SD card to create new image

### ISSUE THREAD

**Issue by conrad9900** [guysoft/FullPageOS#365]
Hi there,
Is there any way that I can edit fullpageos-wpa, fullpageos.txt and clone that as an image so that i do not need to enter the same wifi details and target address each time? I have tried using windisk32imager but it creates an image the total size of the SD card. Even with the option to copy only active partitions.

**Comment by guysoft** [comment]
You can either compress the image you are creating using the proper tools: https://github.com/qrti/shrink (The script according to the readme would work on a Pi or a windows machine running a VM).
Or you can create a variant of FullPageOS: https://github.com/guysoft/FullPageOS#building-fullpageos-variants
