### ISSUE TITLE
WebPage Login?

### ISSUE THREAD

**Issue by gonzabrusco** [guysoft/FullPageOS#382]
Hello. Is there a way of automatically login on a webpage? 

Any ideas are welcomed. 

Thanks

**Comment by guysoft** [comment]
You can press ctrl+t and open a new tab, then login from there, if the page remembers to save the password it should work on the full page browser too. 
It generally depends on which site you are using too.

**Comment by gonzabrusco** [comment]
Finally I figured it out. I could install Tampermonkey and run a script to auto login on page load.

**Comment by NiNu1337** [comment]
> Finally I figured it out. I could install Tampermonkey and run a script to auto login on page load.

Is there a ready-made login script that can be adapted to the corresponding page?
