### ISSUE TITLE
How to rotate the screen to a vertical position?

### ISSUE THREAD

**Issue by Ranidpz** [guysoft/FullPageOS#386]
#### What were you doing?

[Please be as specific as possible here]

#### Version of FullPageOS?

[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by plloppii** [comment]
To rotate the screen a few people have mentioned this online. 
You need to edit the `/boot/config.txt` file, and add `lcd_rotate=2`

**Comment by guysoft** [comment]
Added to wiki at: https://github.com/guysoft/FullPageOS/wiki/FAQ#how-to-rotate-the-screen-to-a-vertical-position

**Comment by 1liminal1** [comment]
Do you have new instructions for bookworm?

**Comment by guysoft** [comment]
@1liminal1 Did you try following it on bookworm and failed? Where did you get stuck?

**Comment by 1liminal1** [comment]
Thanks for getting back, so the Pi 5 has a different display controller (not sure if that's the right terminology) but here 

https://www.raspberrypi.com/documentation/computers/configuration.html#setting-your-displays-resolution-and-rotation

Im going to test this along with the new nightly, as from the other post, let me know if I can get it from the Raspberry Pi flasher app?

Thanks mate!

**Comment by cjoshmartin** [comment]
For anyone else having trouble rotating on a raspberry pi 3. Here are the line I added to the `scripts/start_gui` file to rotate the screen: 

```
export DISPLAY=:0
```

**Comment by guysoft** [comment]
``start_gui`` should have that variable exported at boot time, since its running as part of of lightdm session. How did you execute it that it was not there? Via SSh?

**Comment by wayhdo** [comment]
How about friends, I have tried the steps you say but as soon as I delete #dtoverlay=vc4-kms-v3d the screen loads the entire sequence vertically but at the end of the loading it goes black as if waiting for something

**Comment by cjoshmartin** [comment]
@guysoft yeah via ssh

**Comment by iminimini** [comment]
Is there an update how you can make this work with bookworm? Following the wiki with a Pi 5 and FullPageOS 0.14 did not work for me (nothing is rotated at all)
The documentation @1liminal1 mentioned says you only can rotate the screen with specifying the display name in command line? For my setup I would much prefer a simpler solution in config.txt that works with any display.

**Comment by 1liminal1** [comment]
I ended up using Dakboard in the end, this was too much stuffing around for my little brain lol

**Comment by iminimini** [comment]
@guysoft ok interesting. For now I used standard Pi OS with a script that opens chromium after boot and rotated the screen manually via the UI. But thank you, I will give it another try with FullPageOS then

**Comment by bamasse** [comment]
I want to summarize the helpful info that made FullPageOS work for me with a Pi3 on a rotated screen, so here's a step-by-step for any other wayward soul.
- Connect your pi to the network, wired or wirelessly (modify the wifi.nmconnection file on the SD card to set up wifi) 
- Check your router to to identify the IP address of the "fullpageos" device
- SSH into that IP address, standard port 22. I like to use PuTTY, personally.
- Username is pi and password is raspberry
- `sudo nano scripts/start_gui`
- add `export DISPLAY=:0` to the file, I put it on the second line where there was already an empty line
- Change the seventh line to `DISPLAY_ORIENTATION=left` (or right, or inverted)
- CTRL+O and then Enter to save the changes
- CTRL+X to exit
- sudo reboot
And that should give you a rotated display. But it runs at a REALLY low framerate. DOG slow. It updates like a rolling shutter. If I figure that out, I'll edit this comment.
