### ISSUE TITLE
IFrame different acting

### ISSUE THREAD

**Issue by marsmaennchen** [guysoft/FullPageOS#387]
i am using ioBroker. The visu from ioBroker i´m displaying on a touch screen plugged per HDMI to a Raspberry PI3.
Since 1 day  it shows an IFrame not in the way I configured it.
In ioBroker I can choose a Widget and include the HTML Code:
`<iframe style="transform-origin: 200px 150px ; transform: scale(0.8); width: 400px; height: 1000px;" 

src="https://www.klosterschule-neusiedl.at/index.php/allgemeines/speiseplan#speiseplan" name="iFrame" scrolling="no"></iframe>`

I´m using the version 0.12.0

Here you can see the IFrame in the Visu shown on a Windows PC in the correct way:
![mealcorrect](https://user-images.githubusercontent.com/33393715/136603691-32f6c33b-88c9-4304-a317-abef707ccbe9.JPG)

This is how it´s shown since 1 day, without any manipulation from my side:
![meals1](https://user-images.githubusercontent.com/33393715/136603841-9803f038-24aa-427e-a418-12f1a2445d93.JPG)

And this is once more the HTML config from ioBroker:
![mealconf](https://user-images.githubusercontent.com/33393715/136603921-b1cfcbda-0cc1-4c27-a6f3-c71c7dd7a058.JPG)

I think it´s any problem with the orgin?
Can you help me whats the fault? And why it already worked?
Greetings Patrick

**Comment by guysoft** [comment]
it might be something with FullPageDashboard - did you try showing this without using FullPageDashboard? Aka put the url directly in fullpageos.txt in the /boot folder
