### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by havenonick** [guysoft/FullPageOS#396]
#### What were you doing?

Trying to display a webpage with Emojis on it.

#### What did you expect to happen?

Show the Emojis

#### What happened instead?

Funny symbols showed up.

#### Version of FullPageOS?

Newest from today.

**Comment by guysoft** [comment]
Duplicate of #378

**Comment by guysoft** [comment]
@havenonick There is a fix in master that is not released, If you can try the latest nightly, it should solve the issue (and it would be great if you can report back to #378
