### ISSUE TITLE
Current nightly does not start in kiosk mode

### ISSUE THREAD

**Issue by guysoft** [guysoft/FullPageOS#401]
#### What were you doing?
Flash nightly 2022-02-02

#### What did you expect to happen?

Chromium should load in kiosk mode

#### What happened instead?

got a boarder of the window manager

#### Version of FullPageOS?

nightly 2022-0202

#### Screenshot(s) showing the problem:

![20220205_133835](https://user-images.githubusercontent.com/325670/152641060-e16dcb4e-aeda-4141-a8cd-148ba9315c49.jpg)

Related: https://github.com/guysoft/FullPageOS/issues/400#issuecomment-1030606800

**Comment by Automatica-Mat** [comment]
I have the same issue. When I change the boot page it first starts boardless and then after a minute a border appears. It's like its running the full page script again after a minute and making a border.

**Comment by StanSmits** [comment]
Having same issue, The site is running fine, but the borders are here. Running version Nightly released on 2022-01-25 from raspberry pi imager

**Comment by Gioz1979** [comment]
Having the same issue on 2021-04-14_2021-03-04-fullpageos-buster-armhf-lite-0.12.0 after a manual upgrade to bullseye; I tried to intercept a 'fullpagechange' event in javascript but no success

**Comment by AidanHak** [comment]
Is there any way to force kiosk mode in the meantime?

**Comment by StanSmits** [comment]
> Is there any way to force kiosk mode in the meantime?

"Force" just press f11 on a keyboard

**Comment by dampfklon** [comment]
I think the issue is not chrome. Afaik kios mode in chrome simply hides menus like the adress bar and such.

I changed the command `matchbox-window-manager &` to ` matchbox-window-manager -use_titlebar no &` in the file `/home/pi/scripts/start_gui` which starts the windwo manager without the title bar.

**Comment by guysoft** [comment]
@dampfklon thanks for the workaround. I wonder though if there is a way to make kiosk go to fullscreen. Since that setup would mean that when you press ctrl+t for a new tab, the new tab will not have any title bar neither. I haven't had the time to play with it more, since I am working on the rpi-imager fork and OctoPi first

**Comment by guysoft** [comment]
Ok, so kinda amusing why this happened: chromium made ``--kiosk`` go full screen.
So the command here is not required anymore and actually exists full screen: https://github.com/guysoft/FullPageOS/blob/b1793c7344670cea3e2f6406dac95f1a352cf7d1/src/modules/fullpageos/filesystem/home/pi/scripts/run_onepageos#L6
