### ISSUE TITLE
Rotate Grafana Playlist

### ISSUE THREAD

**Issue by GeekyTim** [guysoft/FullPageOS#402]
#### What were you doing?
Viewing Grafana Playlist

#### What did you expect to happen?
Playlist would rotate between views

#### What happened instead?
Stayed on first page of playlist

#### Was there an error message displayed? What did it say?
None

#### Version of FullPageOS?

0.12.0

**Comment by guysoft** [comment]
Are you using fullpagedashboard? or some feature in grafana?

**Comment by GeekyTim** [comment]
It's a Grafana thing, but I might have worked it out. Will know more
tomorrow.

**Comment by GeekyTim** [comment]
Good news: This is not your fullpageos which is at fault, but the URLs
exposed by Grafana. I thought I had the playlist URL, but had a page URL.

Please close this 'issue'

*Thanks*

*Tim Richardson*
*Twitter: @Geeky_Tim*

**Comment by guysoft** [comment]
Thanks for updating
