### ISSUE TITLE
Hi - is it possible to change the orientation to portrait instead of landscape ? I need the monitor to be vertical...

### ISSUE THREAD

**Issue by hurtigkarl** [guysoft/FullPageOS#407]
#### What were you doing?

[Please be as specific as possible here]

#### Version of FullPageOS?

[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment]
Duplicate of: #386
