### ISSUE TITLE
Ability to not disable DPMS and screen blanking

### ISSUE THREAD

**Issue by thedumbterminal** [guysoft/FullPageOS#410]
#### What were you doing?

Running a raspberry pi with a touchscreen, but I want the display to turn off when idle as normal.

#### What did you expect to happen?

A configuration option to stop DPMS and screen blanking.

I know this distro is for kiosk operation so maybe disabling DPMS would be the default and any such option would stop this behaviour.

#### What happened instead?

I had to remove the first few lines of the script:

/home/pi/scripts/start_gui

However I can't find the source of this file in: https://github.com/guysoft/FullPageOS/tree/devel/src/modules/fullpageos/filesystem/home/pi/scripts

#### Version of FullPageOS?

0.12.0

**Comment by guysoft** [comment]
You are welcome to send a Pull Request with a script that disables it. I am not implementing it because I have no time for it.

**Comment by thedumbterminal** [comment]
No problem, do you know where the source of `/home/pi/scripts/start_gui` resides in github?

**Comment by guysoft** [comment]
> No problem, do you know where the source of `/home/pi/scripts/start_gui` resides in github?

Here: https://github.com/guysoft/CustomPiOS/blob/devel/src/modules/gui/filesystem/home/pi/scripts/start_gui

You can place a script at ``modules/gui/filesystem/home/pi/scripts``. 
That lets you switch if off, or on/off.

**Comment by thedumbterminal** [comment]
I've put a PR into CustomPiOS as this is not a specific FullScreenOS issue. Let me know if the approach is suitable, thanks for the quick replies.

**Comment by guysoft** [comment]
Merged the changes, also thanks for the rotation option touch.
Should this issue be closed?

**Comment by thedumbterminal** [comment]
yup, nothing left to do here, thanks.
