### ISSUE TITLE
Youtube video doesn't play

### ISSUE THREAD

**Issue by Carlos-MVP** [guysoft/FullPageOS#415]
#### What were you doing?

I have a wordprees site which shows a video from youtube and a few images

What did you expect to happen?
I expected the youtube video to play automatically.

What happened instead?
The video does not start, until I click.

Was there an error message displayed? What did it say?
there was no error displayed

Version of FullPageOS?
00.12.0
is there a way to config this ?

**Comment by guysoft** [comment]
Can you provide a url? I can't test without an example

**Comment by Carlos-MVP** [comment]
I already solved my problem, it's nothing related to fullpageos.
I just had to enable sound permission on my website from chromium settings.

Thanks for your attention, the project is great.
