### ISSUE TITLE
TTY X won't open using Ctrl+Alt+FX

### ISSUE THREAD

**Issue by hankerspace** [guysoft/FullPageOS#417]
Hello,

I am working on old FullpageOs versions in order to get a browser flash-compliant.

I am using the 2020-02-13-fullpageos-buster-lite-0.12.0.img, which is the only version with RPI4 full support and Flash in browser full support.

Howerver for some reasons I can't use TTY with Ctr+Alkt+FX shortcut...

Using F1->F6 just hides the mouse cursor from the screen, nothing else changes, the X desktop remains open.
With F7 the mouse cursor shows up back.

Any ideas ? It could be great if I can fix by editing some files in the OS.

Thanks ;) Best.

**Comment by guysoft** [comment]
Hey,
I just flashed and booted this nightly, though I am stressing that I am not planning to maintain this, and don't expect any support.
And I tested and the keyboard did work. However it took a short while to start, I warmly suggest you plug in a mouse too and try and test the keyboard works by clicking on the + sign and typing in to the fields.
