### ISSUE TITLE
Problema AUDIO!!! 

### ISSUE THREAD

**Issue by Loryracing** [guysoft/FullPageOS#431]
#### What were you doing?

Non mi funziona l'audio tramite cavo Hdmi. 

#### Version of FullPageOS?

[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

#### If you are building FullPageOS - provide a build.log that is created for the build

Problema audio tramite Cavo Hdmi, come faccio ad abilitarlo? Grazie.

**Comment by guysoft** [comment]
Might be related to:
#429

What version of FullPageOS?
