### ISSUE TITLE
Howto

### ISSUE THREAD

**Issue by JEB67** [guysoft/FullPageOS#435]
Howto remove ad blocker?
There are pages that verify the ad blocker and if it is active they do not allow you to view the page or perform different actions...
That is why I need that when loading the operating system the blocker is disabled.
It's possible?
Thanks.

**Comment by guysoft** [comment]
It comes built in raspberypi official image. I am not sure how to remove it apart from manually uninstalling it. You can ask raspberrypi/chromium maintainer how they did it and how to remove it

**Comment by JEB67** [comment]
OK Thanks.
