### ISSUE TITLE
Pages reloading on tab switch? How to turn that off?

### ISSUE THREAD

**Issue by mano1979** [guysoft/FullPageOS#445]
#### What were you doing?

When the tabs are being switched, the pages are reloading. Meaning that the more data is on the page, the longer it will take to load. So now i get white flashes before the next tab is shown, which is really annoying. Is it possible to turn this off? So once the page is loaded once, it doesn't have to be reloaded?

#### Version of FullPageOS?

0.13

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment]
Take a look at: https://www.chromium.org/chromium-os/chromiumos-design-docs/tab-discarding-and-reloading/
