### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by arpanet999** [guysoft/FullPageOS#455]
#### What were you doing?

So i have just installed FullPageOS on a Raspberry PI 3B
Everything works on my computer screen. Like it is supposed to.
Then i move it to another location with another screen. 
i see the Boot process. The logo shows and all. and when the kiosk mode is suppose to happend it just goes black. Not even the mouse is there. It has network trough cable. same cable as before so no problem there. i have tryed connect to wifi but nothing. When i reconnect to the first screen it works but movint it to the other screen a couple meters away then that problem occurs.
Its an Samsung S32A600UUU S60a 32" QHD VA 16:9 2560x1440 screen.

#### Version of FullPageOS?
i took this one from you mirror.
2021-04-14_2021-03-04-fullpageos-buster-armhf-lite-0.12.0.zip

**Comment by guysoft** [comment]
@Cenedd do you think its worth to add this in to the wiki? Any idea under what category?

**Comment by Cenedd** [comment]
Definitely, yes.  Under 'Assorted Guides'? There didn't seem to be much on the issue from any source other than setting HDMI safe mode.  That does work with straight Raspbian but it is essentially a superset of other options and one of the things it does is limit resolution to VGA. It also didn't help until after a full apt upgrade.
I'm not sure why this happens with a new batch of Pi 4's and not with the old.  I'm guessing firmware but realistically the only way is forward with that.
I've no idea how much work I'm asking here but would it be worth putting out a new build that just updates everything around FullPageOS?  Essentially doing the apt update, apt upgrade in advance.  The config.txt options could be preset but can be set directly in text files on the card.  To do an upgrade over SSH with no screen output adds a hurdle that a lot of people are going to give the whole thing a miss.

**Comment by guysoft** [comment]
Sounds like an FAQ entry: https://github.com/guysoft/FullPageOS/wiki/FAQ
Added: https://github.com/guysoft/FullPageOS/wiki/FAQ#my-display-works-on-a-computer-screen-but-not-on-another-display
You are welcome to change it if you think it needs changes
