### ISSUE TITLE
Every other safe_refresh call I make in crontab leads to a blank page with the Chrome Web Store icon

### ISSUE THREAD

**Issue by MKaidan** [guysoft/FullPageOS#459]
#### What were you doing?

Using crontab to safe_refresh the page every day (twice a day).

#### What did you expect to happen?

The page would refresh successfully.

#### What happened instead?

The page goes to a blank screen with the Chrome Web Store icon in the middle.

#### Was there an error message displayed? What did it say?

No.

#### Version of FullPageOS?

0.13.0

#### Screenshot(s) showing the problem:

![2023-03-27 14_18_35-OV-DIR-L (OV-DIR-L) - VNC Viewer](https://user-images.githubusercontent.com/77799466/228031138-ede6d82c-15d9-449d-8662-6a241748eb32.png)

**Comment by MKaidan** [comment]
After a reboot, now I get this error when I perform `safe_refresh`:
```
Refreshing page.
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
```

**Comment by MKaidan** [comment]
After a second reboot, things are back to normal, but what could be causing these issues?

**Comment by guysoft** [comment]
Looks there is something wrong with your display - how are you connecting to the Pi? I might be that DISPLAY environment variable is not set correctly, or you are using SSH with X forwarding:
https://unix.stackexchange.com/questions/199891/invalid-mit-magic-cookie-1-key-when-trying-to-run-program-remotely

**Comment by MKaidan** [comment]
Why would any of these be the issue with a standard FullPageOS install?

**Comment by guysoft** [comment]
It depends how you are connected to it. Over ssh, a virtual terminal or terminal inside the graphical interface. These would yield different results

**Comment by guysoft** [comment]
Who is "We"?

This needs to be set correctly:
https://datacadamia.com/ssh/x11/display
