### ISSUE TITLE
How do I get touch to work?

### ISSUE THREAD

**Issue by ablohme86** [guysoft/FullPageOS#469]
#### What were you doing?
Trying to touch the screen
[Please be as specific as possible here]

#### What did you expect to happen?
The touch to act as a mouse
#### What happened instead?
Nothing
#### Was there an error message displayed? What did it say?
Nope
#### Version of FullPageOS?
2023-05-13_2023-05-03-fullpageos-bullseye-armhf-lite-0.13.0.zip.md5
[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment]
What type of touch screen?
Have you taken a look at this in the wiki?
https://github.com/guysoft/FullPageOS/wiki/PI-3.5-inch-Touchscreen

**Comment by guysoft** [comment]
Closing if no reply
