### ISSUE TITLE
Blinking box in the top right?

### ISSUE THREAD

**Issue by spencerscan** [guysoft/FullPageOS#47]
Anyway to disable this?  Thanks

**Comment by guysoft** [comment]
Can you be more specific?
Sounds like it might not be connected to FullPageOS

**Comment by spencerscan** [comment]
It's working great, however there is a fading box divided in 4 colors (red,yellow,blue,green) in the top right corner.   It fades in and out every couple seconds.

**Comment by guysoft** [comment]
Can you photograph it?

**Comment by spencerscan** [comment]
![img_6559](https://cloud.githubusercontent.com/assets/20373000/16710285/0f4611f6-45f7-11e6-99c2-ccaa4afe31e6.JPG)
Sure can!  Attached is the block I'm talking about

**Comment by jtyle6** [comment]
Under-voltage warning.

https://www.raspberrypi.org/forums/viewtopic.php?t=82373
