### ISSUE TITLE
script ./reload_fullpageos_txt does not work, fix at bottom of issue

### ISSUE THREAD

**Issue by wabash1** [guysoft/FullPageOS#471]
#### What were you doing?

executed ./reload_fullpageos_txt in /scripts

#### What did you expect to happen?

chrome to reload

#### What happened instead?

chromium-browser-v7 no such file or directory

#### Was there an error message displayed? What did it say?

chromium-browser-v7 no such file or directory

#### Version of FullPageOS?

nightly

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

#### If you are building FullPageOS - provide a build.log that is created for the build

FIXED by editing script to killall /usr/lib/chromium-browser/chromium-browser 
(remove the -v7)

**Comment by guysoft** [comment]
Thanks fixed

**Comment by wabash1** [comment]
Thank you!
