### ISSUE TITLE
Failing to fetch data

### ISSUE THREAD

**Issue by SamuelVanhaecke** [guysoft/FullPageOS#476]
#### What were you doing?

I have a Next.js application that I want to run on FullPageOS, when opening the webapp in a browser on my laptop everything works fine but when running on FullPageOs I get a failed to fetch error. I am getting my data from MongoDB.

#### Version of FullPageOS?

Latest version

**Comment by guysoft** [comment]
What is the URL on your laptop - could it be that you are serving a
webserver on your laptop that only works on localhost?

**Comment by SamuelVanhaecke** [comment]
Hi, thank you for the quick response. The app is hosted on Vercel and on my laptop it works when I open it from the Vercel URL.
