### ISSUE TITLE
Disable Google-Translate-Popup

### ISSUE THREAD

**Issue by stritti** [guysoft/FullPageOS#478]
#### What were you doing?

Starting German page in fullscreen, there pops up an translation dialog of Google Translate.

#### What did you expect to happen?

No popup should be shown.

I think there should be one param updated at https://github.com/guysoft/FullPageOS/blob/b810bf882edb763de96532de2265f14162c8d065/src/modules/fullpageos/filesystem/home/pi/scripts/start_chromium_browser#L4 

from:

```sh
chromium-browser [...] --disable-features=Translate [...]
```

to:

```sh
chromium-browser [...] --disable-features=TranslateUI [...]
```
I used this in selfmade Kiosk sucessfully.

#### What happened instead?

Popup is shown as shown in screenshot below

#### Version of FullPageOS?

0.12.0

#### Screenshot(s) showing the problem:

![IMG_1640](https://github.com/guysoft/FullPageOS/assets/184547/ab019761-d9b0-427a-90cf-1c72d9110027)

**Comment by guysoft** [comment]
Thanks for reporting, looks like it changed:

https://github.com/GoogleChrome/lighthouse/discussions/11860

https://chromium-review.googlesource.com/c/chromium/src/+/2404484

**Comment by nightvisi0n** [comment]
@guysoft It seems the google translate popup is showing again in the latest FullPageOS image. Reverting [ef1a399](https://github.com/guysoft/FullPageOS/commit/ef1a399f6f60374f4d9c240897d98a8b02e4f226) fixes it, so it seems they reverted the feature name back to `Translate`.

**Comment by guysoft** [comment]
@nightvisi0n any idea why it would change? Sounds strange. did chromium change and then change back?

**Comment by nightvisi0n** [comment]
Yep, kind of strange. I don't have a clue why they would change it back.
I can check my chromium version if you want, just to be sure I'm not using an old version. But I don't think so as I did a fresh install of FullPageOS through the raspberry pi imager.

**Comment by nightvisi0n** [comment]
@guysoft Any chance this could be fixed, or should I open a new issue for that?

**Comment by guysoft** [comment]
@nightvisi0n this was fixedx and happend again.
Lets find a way to fix this once and for all - I am working on an end-to-end test framework for FullPageOS (and CustomPiOS in general). I lets us run tests without booting and testing on a pi directly.
I think this constitutes adding a test that checks a webpage that has translation, and confirms if the popup appears or not - can someone provide a webpage where this reproduces so I can add a test around it?
