### ISSUE TITLE
Possible to let website run commands?

### ISSUE THREAD

**Issue by Stiwen02** [guysoft/FullPageOS#481]
Is it possible to let website run system commands? For example letting the website run ``sudo shutdown -h now`` or ``sudo mkdir downloads`` with JavaScript code like ``system("sudo shutdown -h now")``, without asking for any permissions?

**Comment by guysoft** [comment]
In order for a browser to run a physical command on a device, you need to write a backend. A server that would receive that command and execute it.
This though not a FullPageOS issue, its the system architecture of the world wide web.
