### ISSUE TITLE
Is it possible to Connect to HDMI Screens?

### ISSUE THREAD

**Issue by madakuoni** [guysoft/FullPageOS#483]
I am using an Raspberry Pi 4 with FullpageOS Right now. At the Moment i use one screen on the First HDMI out. I would Like to change this setup. 
I'd Like to Show 2 Websites with 2 different Screens One Page per HDMI Output. Is this possible?

**Comment by guysoft** [comment]
Hey,
Not its not without special configuration.
There are workaround in here:
https://github.com/guysoft/FullPageOS/issues/364#issuecomment-776713693
Closing as duplicate
