### ISSUE TITLE
FullpageOS (Stable) is giving a 404 when trying to install via Raspberry Pi Imager v1.7.5 on macOs

### ISSUE THREAD

**Issue by ekeyur** [guysoft/FullPageOS#484]
#### What were you doing?
Install FullpageOS (stable) version using Raspberry Pi Imager

#### What did you expect to happen?
FullpageOS to install without any snags

#### What happened instead?
There was a 404 error when trying to download the version

#### Was there an error message displayed? What did it say?
See attached screenshot
#### Version of FullPageOS?

[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:
<img width="667" alt="fullPage" src="https://github.com/guysoft/FullPageOS/assets/19393644/6e771261-d785-4c39-923d-35d631c65dbc">

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment]
Fixed.
The new release was done yesterday and the imager update code failed on the first run.
