### ISSUE TITLE
Removing lighthttpd

### ISSUE THREAD

**Issue by cjus** [guysoft/FullPageOS#51]
I'm running a NodeJS app on my Pi and don't have a need for lighthttpd/PHP. Is there a way to remove lighthttpd without building a FullPageOS variant?  

I can do this, but is there a cleaner or recommended approach?

```shell
$ sudo apt-get remove lighttpd
```

**Comment by guysoft** [comment]
``sudo apt-get remove --purge lighttpd`` ?

**Comment by tailorvj** [comment]
@cjus Would you like to help us integrate Node.js + Express http server instead of lighttpd for 0.7.0? We are having a hackathon on July 29-30th

**Comment by guysoft** [comment]
I can make lighttpd optional with a config setting, which would let you build a nodejs variant with ease.

**Comment by tailorvj** [comment]
@guysoft sounds great. Do you think we can have the node.js code running from the SD card? That way we could replace the node app code easily without touching the system
