### ISSUE TITLE
Could you set up a Discussions tab?

### ISSUE THREAD

**Issue by SecularSteve** [guysoft/FullPageOS#512]
I feel like it would be necessary for this software.

A place where people can discuss the best way to use it, essential sites, tips, tricks, where they can give their own examples and make suggestions without cluttering the issues page.

But that's just my suggestion.

**Comment by guysoft** [comment]
Great idea, should have thought of it myself, I think I was thinking of a discourse and got stuck setting that up.

Done:
https://github.com/guysoft/FullPageOS/discussions/513

**Comment by SecularSteve** [comment]
Thank you and much obliged 👍
