### ISSUE TITLE
suspend in stable version 2022

### ISSUE THREAD

**Issue by frosstatx** [guysoft/FullPageOS#515]
After 15 minuter in raspberry model 4 in the stable version  enter a suspend mode,  how i can disable this?

**Comment by csabal** [comment]
Are you sure it is your Raspbi? Check your monitor / TV  sleep settings as well.

**Comment by guysoft** [comment]
Testing on another monitor might help

**Comment by smadds** [comment]
I am seeing the same - if I have a mouse plugged into the Pi and move it the screen comes alive again. Not sure if it's going into standby or just screen blanking. I have disabled screen blanking in raspi-config.

**Comment by guysoft** [comment]
I am moving this to a discussion, since it talking about an older version and is not planned to be fixed retrospectively (and does not look like a bug)
