### ISSUE TITLE
 FullPageOS (Nightly) - HELP!

### ISSUE THREAD

**Issue by Guruabyss** [guysoft/FullPageOS#520]
Hardware: Raspberry Pi 5

OS: FullPageOS (Nightly) Release: 2024-02-19

Setup:
1) Using the Raspberry Pi Imager v1.8.5 at the last step after picking my storage device it asks if I want to "apply OS Customization settings" in which I setup the Usr/Pw, Wifi, SSH enabled. The OS install, verifies the build all is "good".

2) take out the USB/ SD card reader and put it back into the PC so I can edit fullpageos-wpa-supplicant.txt in which I add the Wifi Info again. Then I edit the fullpageos.txt to add in the URL I want it to go to.

Problem:
1) Pi boots, shows a screen at first that says "Generating SSH Keys... Rebooting in 5 seconds.... After the reboot it goes through it's normal boot loading process (as far as I can tell) then I get an error "splash.png loading FAILED. It then goes through the boot loading process again and then it dumps me into the OS but it doesn't auto load the browser and go to the website I put in the fullpageos.txt but instead I want's me to put in a Usr/Pw. After I do that I then get the error:

"Xsession: unable to launch "/hone/pi/scripts/start_gui" X session "/hone/pi/scripts/start_gui" not found; falling back to default session."

Now I've followed these tutorials to get an idea of FullPageOS install:
1) https://www.youtube.com/watch?v=pG7j_cuL1gQ
2) https://www.youtube.com/watch?v=90Q8NJgd6KA

I've tried three MicroSD cards and two different USB / MicoSD readers and all the outcomes are the same as above. How is it the YouTube videos that I followed to a T seem so effortless and just works and I'm in a use-case that is no where near what I saw/followed. Please Help!

**Comment by guysoft** [comment]
Nightly is broken, working on it, see #498
