### ISSUE TITLE
Symlink broken!

### ISSUE THREAD

**Issue by csabal** [guysoft/FullPageOS#521]
Symbolic link does not work between the wpa config file, and the fullpageos config file!

It results that if you modify the fullpageos-wpa-supplicant.txt file it does not affect the wifi settings at all!
So, you got only black screen, because there is no net configured (either eth. or wifi)

Check:
ls -l /etc/wpa_supplicant

You should see this:

![2Screenshot 2024-02-14 164145](https://github.com/guysoft/FullPageOS/assets/72354260/58fd7f86-f020-4469-a845-86d5ba87587e)

If not, run this:
sudo ln -sf /boot/fullpageos-wpa-supplicant.txt /etc/wpa_supplicant/wpa_supplicant.conf

And check again!

Reboot, and wifi settings applied.

**Comment by guysoft** [comment]
There is an issue with the bookworm build, see #498
Working on it

**Comment by guysoft** [comment]
See comment https://github.com/guysoft/FullPageOS/issues/498#issuecomment-1962347265
I am closing here, feel free to comment there. 
I also tested wpa supplicant network method setting and it worked.

**Comment by csabal** [comment]
It is still not working!!! Not at all.

If you modify the fullpageos-wpa-supplicant.txt nothing happens, since it is not forward the settings to the wpa_supplicant.conf. 

Unfortunately the above command just don't work anymore.
Nightly built from the PI Imager.

Any help?????

Very sad.

**Comment by csabal** [comment]
OK, so the weird thing it is forward the WIFI data to the wpa_supplicant/ wpa_supplicant.conf BUT the Pi connect to the original WIFI what was given during the install. 

I am confused...and give this up.

**Comment by guysoft** [comment]
Are you using the release candidate from 2024-03-31?
i tested it. Flashing from rpi imager works

**Comment by csabal** [comment]
Yes!

Just try to modify the fullpageos-wpa-supplicant.txt !!! It wont pick up other Wifi, still connecting that one, I entered durign the rpi imager!!!!
