### ISSUE TITLE
Error: Can't open display (null) Failed creating new xdo instance

### ISSUE THREAD

**Issue by andywaite** [guysoft/FullPageOS#54]
I seem to be having an issue with running this.

I get the following on boot:

Error: Can't open display (null)
Failed creating new xdo instance

My Pi is an early model B.

**Comment by andywaite** [comment]
For info, I haven't changed anything except the network config which is set up for wired connection, and edited the URL it loads.

**Comment by guysoft** [comment]
FullPageOS does not work with RaspberryPi 1/Zero/B+ , see #12 
There are talks getting it working here at #43
