### ISSUE TITLE
Disable default shortcuts

### ISSUE THREAD

**Issue by Mikkelsen2005** [guysoft/FullPageOS#550]
#### What were you doing?
I was building a web kiosk and now i want to enchance security and disable all shortcuts so we only can access terminal through ssh.
and the raspberry that is running fullpageos only can access the chrome page that its told to show.

#### Version of FullPageOS?
0.14.0

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment]
Duplicate of:
https://github.com/guysoft/FullPageOS/issues/264

There are a few talks there.
