### ISSUE TITLE
Custom Splash screen only working for 1 frame then default red FULLPAGEOS splash is displayed until boot finish

### ISSUE THREAD

**Issue by MrCO0OL** [guysoft/FullPageOS#559]
#### What were you doing?

replaced the /boot/firmware/splash.png to a new custom splash file 

#### What did you expect to happen?

I expected my new custom splash screen to be displayed during booting time and stay visible till chromium starts

#### What happened instead?

my custom splash screen only been displayed for less than a second during booting .... then again the default red splash screen of FULLPAGEOS get displayed again and stayed persistent till boot finish and chromium starts

#### Was there an error message displayed? What did it say?

no error messages

#### Version of FullPageOS?

0.14.0

**Comment by guysoft** [comment]
So the truth is FullPageOS does a small trick to have the splash screen on as long as possible - its also the background once the UI starts.

You also need to change:
```
/opt/custompios/background.png
```

See:
https://github.com/guysoft/FullPageOS/commit/89e3f9ae88a38e86158fdebf32976f7b207c254c
