### ISSUE TITLE
FullPageOS is staying on the splash screen.

### ISSUE THREAD

**Issue by cenktrms** [guysoft/FullPageOS#569]
#### What were you doing?

Boot

[Please be as specific as possible here]

#### What did you expect to happen?

Open my page and show.

#### What happened instead?

Stayed on FullPageOS boot screen with mouse cursor.

#### Was there an error message displayed? What did it say?

No error message.

#### Version of FullPageOS?
0.14.0
raspberry pi 5

[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

![IMG_6967](https://github.com/guysoft/FullPageOS/assets/15123025/f19975fe-08cd-48b0-bd0d-128ac9b6efa3)

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment]
If you see the splash screen and a cursor it means that the GUI has loadad, its the background of the desktop. And the browser is not switching on because its waiting for an internet connection

**Comment by guysoft** [comment]
@rafael-monkeysoft 
security.org is not a registered domain to you, I assume the error is that you don't have a signed certificate for https, also its strange doing https on port 8085

**Comment by carloavilam-gif** [comment]
anyone with a response to this issue? my fullpageos was working perfect yesterday until i modified the site it was meant to run (same domain, i updated the site´s content). i cant seem to get it to work.  some sites like youtube.com will work. i tried making my site much lighter and that didn´t seem to make it work. this is my site https://elcafeki.wixsite.com/menu-ki

**Comment by guysoft** [comment]
@carloavilam-gif
Assuming you can see a mouse already - can you see a mouse cursor?
If so it means you are passed the splash screen and its actually the desktop background.

It might be that FullPageOS is unable to connect to the url, it will not open until it can curl to the page:
This is the logic:

https://github.com/guysoft/FullPageOS/blob/devel/src/modules/fullpageos/filesystem/opt/custompios/scripts/run_onepageos

You can try set:
```
echo disabled > /boot/firmware/check_for_httpd
```

**Comment by carloavilam-gif** [comment]
i tried doing so but it could not find the path.
it will sometimes log half the page. half of the pictures will be unable to load

**Comment by guysoft** [comment]
@carloavilam-gif That sounds like a connectivity issue. Check your dmesg for connection or other IO errors
