### ISSUE TITLE
x11vnc will fail on no-default pi user needs to be changed to be user-independent

### ISSUE THREAD

**Issue by guysoft** [guysoft/FullPageOS#571]
See here, has user pi:

https://github.com/guysoft/FullPageOS/blob/devel/src/modules/fullpageos/filesystem/root_init/etc/systemd/system/x11vnc.service#L7

Needs to be changed to something global

**Comment by romankysely** [comment]
I agree. I have great experience with realVNC server instead  preinstalled x11VNC. I suggest to chang it at image. x11VNC is very slow nad demanding sources I think. 
RealVNC is following system/user password.
Or maybe consider to  preinstall Pi Connect service which is no require static public IP at all. But I do not have practical experience with it.

**Comment by guysoft** [comment]
@romankysely I have no time to implement that, but would accept PRs if you have something that works.
