### ISSUE TITLE
Disabling local lighthttp prevents starting of the image

### ISSUE THREAD

**Issue by semanticfire** [guysoft/FullPageOS#60]
if you use:
FULLPAGEOS_INCLUDE_LIGHTTPD=no

The chromium browser will not come up due to the wait for a '200' from the localhost in:
https://github.com/guysoft/FullPageOS/blob/devel/src/filesystem/home/pi/scripts/run_onepageos#L10
Which will never happen since there is not http listening

**Comment by guysoft** [comment]
That is the point, it is there to let variants disable httpd, for example if you want to install nodejs as a server.
