### ISSUE TITLE
Any plans on having arm64 build?

### ISSUE THREAD

**Issue by AyrtonRicardo** [guysoft/FullPageOS#600]
#### What were you doing?

while installing multiple packages I found the difficult of arm(32bit) system using amhf instead of arm64, therefore I asked myself if there is any plan on having nightly build on arm64 version of it.

I will build it myself, but even so I wanted to know if there is plans for this to happen in the main repo.

**Comment by guysoft** [comment]
I really don't have time to maintain one.
You are welcome to build and maintain one yourself, I can lend a hand, its pretty easy to build with CustomPiOS v2.

```
sudo docker exec -it fullpageos-build build -d -b raspberrypiarm64
```

Using docker compose in this repo under src:
```yaml
services:
  custompios:
    image: guysoft/custompios:devel
    container_name: fullpageos-build
    tty: true
    restart: always
    privileged: true
    volumes:
      - ./:/distro
    devices:
      - /dev/loop-control```
