### ISSUE TITLE
How do you use variants to override run_onepageos

### ISSUE THREAD

**Issue by semanticfire** [guysoft/FullPageOS#61]
I've created a variant directory.
The config file is processed nicely,
I've modified and copied the post_chroot_script to unpack the home directory
but the file from my variant directory 
`filesystem/home/pi/scripts/run_onepageos `
is not used to create the image.

**Comment by guysoft** [comment]
Its part of ``pre_chroot_script``/``post_chroot_script``

Add to ``post_chroot_script``:

    unpack /filesystem/home/pi /home/pi pi

**Comment by semanticfire** [comment]
Thanks that solved my problem!
