### ISSUE TITLE
Two webpages

### ISSUE THREAD

**Issue by patranjo** [guysoft/FullPageOS#68]
Is there a way to have two different webpages load and switch between them with gpio button press.

**Comment by guysoft** [comment]
Please look at FullPageDashboard.
Regarding GPIO buttons, no you will need to write it.

**Comment by patranjo** [comment]
Is there anyway to disable the timed rotation in FullPageDashboard where it just stays on one tab until something tells it to switch.

**Comment by guysoft** [comment]
Not without editing the source code

**Comment by patranjo** [comment]
Thanks
