### ISSUE TITLE
Change fullpageos.local to my own host

### ISSUE THREAD

**Issue by JorgeFrancoIbanez** [guysoft/FullPageOS#71]
HI, im triying to change the host fullpageos.local to raspi1.local and raspi2.local because i need to acces to two raspPi3 and if they have the same host. this will generate a problem. Any suggestion?

**Comment by guysoft** [comment]
Its the same as any raspbian distro.
There are two ways you can do it.
1. Either by using raspbi-config. As [described here](http://geek-university.com/raspberry-pi/change-raspberry-pis-hostname/).
2. Directly editing two files on the Pi. Change the word ``fullpageos`` there to your desired hostname.
``sudo nano /etc/hosts``
and:
``sudo nano /etc/hostname``
Then reboot
