### ISSUE TITLE
Limited Browser size

### ISSUE THREAD

**Issue by tannert2** [guysoft/FullPageOS#72]
I am trying to set up a dashboard to have multiple tabs rotating, but for some reason the page only takes up a small portion of the screen. Any fix for this? Below is an image of what I am seeing. 

I only have this problem when I try to set up the dashboard. When I display only one webpage it works fine.

![snip_20160908100351](https://cloud.githubusercontent.com/assets/22078072/18352298/da6acf46-75ab-11e6-8bb7-24792baa2a04.png)

**Comment by guysoft** [comment]
Known bug. At the moment the only way around it is to not use FullPageDashabord. 
This can be done by chanigng the url in ``/boot/fullpageos.txt`` to your desired url. This can also be done on a windows machine.

**Comment by tannert2** [comment]
Ok, thank you for your response. That is how I set it up the first time then thought I would try out the dashboard.  If you don't mind could you add an update to this issue thread when the problem is fixed.

**Comment by guysoft** [comment]
Of course, will also link duplicates reports here. Its how we roll.
Also @tailorvj is sort if assigned to this. But we are all busy and it
would require replacing FullPageDashboard

**Comment by guysoft** [comment]
This issue has been fixed with commit https://github.com/amitdar/FullPageDashboard/commit/59f847f447f3bac0369a4ff7fde6455b7e6cd1c5
