### ISSUE TITLE
Path in md5 file is absolute

### ISSUE THREAD

**Issue by uda** [guysoft/FullPageOS#73]
The .md5 files for the zips in the mirror contain absolute paths to the files as they were on the jenkins machine, they should be relative, so when downloaded we can check them while they are in the same directory.

In the script running `md5sum` cd to `/var/lib/jenkins/workspace/FullPageOS/` before generating the md5 file.

**Comment by guysoft** [comment]
Should be fixed in next nightly

**Comment by guysoft** [comment]
Next nightly is out and it works
