### ISSUE TITLE
Use chromium bundled with New Raspbian PIXEL version 2016-09-23

### ISSUE THREAD

**Issue by guysoft** [guysoft/FullPageOS#75]
Ok good news. Looks like the Pi foundation released a new build of chromium that they are bundling with the official RaspberryPI.
[See release note:s for 2016-09-23](http://downloads.raspberrypi.org/raspbian/release_notes.txt).
`* Chromium web browser included`.
It seems like it will also use the hardware acceleration in the Pi for video playback. So this fixes a lot of issues at once
This has a potential to fix the following issues:
#66 #29 #22

**Comment by rojepp** [comment]
Looking forward to this. Wish I knew how to help.. :-/

**Comment by guysoft** [comment]
At the moment the build is getting ``Hash Sum mismatch`` errors, so we need to wait till the repos start working again.

**Comment by tailorvj** [comment]
It seems like we'd forecast the PIXEL release :) It also includes VNC and node.js out of the box

**Comment by anthonywebb** [comment]
Has this been integrated yet in the nightly builds?  We are trying to set up some devices but would prefer to have the latest and greatest

**Comment by anthonywebb** [comment]
@guysoft you think fullpageos will work with this latest release from pi foundation?  I'd like to give it a try when it is ready.  Thanks!

**Comment by anthonywebb** [comment]
For those of you hoping that the new chromium build would solve the mp4 playback issues, it appears to have helped a bit, but its in no way a replacement for omxplayer, the new pixel interface is great though

**Comment by guysoft** [comment]
Ok,
So here is a new build, I didn't pay with the chromium installation yet, so I encourage you guys to try and install the PIXEL installation which should be in the repos:
image: http://docstech.net/FullPageOS/nightly/2016-10-20_2016-09-23-fullpageos-jessie-lite-0.7.0.zip
md5 http://docstech.net/FullPageOS/nightly/2016-10-20_2016-09-23-fullpageos-jessie-lite-0.7.0.zip.md5

**Comment by guysoft** [comment]
Ok, had a chance to test that nightly, there dosn't seem to be any`` chromium-browser`` package, only ``rpi-chromium-mods`` which has a flashplugin in it. Any insight would he helpful

**Comment by NoviCMS** [comment]
Great, going to try the PIXEL installation!

**Comment by guysoft** [comment]
I made another PIXEL installation one with the full image, that could also be tested, since I can't see a package for the PIXEL chromium-browser available:
http://docstech.net/FullPageOS/nightly/2016-10-23_2016-09-23-fullpageos-jessie-0.7.0.zip
http://docstech.net/FullPageOS/nightly/2016-10-23_2016-09-23-fullpageos-jessie-0.7.0.zip.md5

**Comment by NoviCMS** [comment]
Oké, i a'm missing the hardware acceleration on my RPI 3, is there any way to enable this? are they working on it?

**Comment by guysoft** [comment]
@NoviCMS 
1. What image are you using out of the 2?
2. How are you testing for acceleration? Are you talking about 2D or 3D?

**Comment by NoviCMS** [comment]
@guysoft 
1: i am using the first image and the master branch
2: i am using the image for my RPI kiosk with touchscreen. (24" 1080p with toch overlay) 
This is my test site: http://in2shop.staging.novisites.nl/shop/526842
when opening a menu or scrolling down the page it becomes laggy. (i have tested many distro's on RPI3)

**Comment by NoviCMS** [comment]
going to try 2016-10-23_2016-09-23-fullpageos-jessie-0.7.0.zip now. i hope the jpg bug is fixed.

**Comment by NoviCMS** [comment]
This build: 2016-10-23_2016-09-23-fullpageos-jessie-0.7.0.zip is by far the best i have seen till now. maybe you could create a build from this one? if i boot the image the browser does not start. also fullpageos.local is not set.

**Comment by guysoft** [comment]
@NoviCMS 
1. Can you be specific to what is good there?
2. The browser does not start in 2016-10-23_2016-09-23-fullpageos-jessie-0.7.0.zip? if so why is it the best?

**Comment by NoviCMS** [comment]
Hey @guysoft 

1: video's play smooth(er), jps are displayed, overall experiënce is better.
2: The browser does not start automatically after boot, i was able to start it using the menu.

**Comment by NoviCMS** [comment]
@guysoft can you create a img from the PIXEL installation with the full image with working fullpageos.local, and browser start?

**Comment by NoviCMS** [comment]
@guysoft i see that the build has gone wrong, at the base there is a folder "filesystem" in there are the config files etc.... i will try to cp all to /

**Comment by guysoft** [comment]
If there is a menu it means the special lightdm session isn't starting.
Thats the problem.

**Comment by NoviCMS** [comment]
no success so far, i will look into it in a couple of days

**Comment by matt7277** [comment]
Using the 10/23 Nightly build on a RaspberryPi 3 and also noticing that Chromium fails to launch. If you launch manually, the http://localhost/Welcome and http://localhost/FullPageDashboard do Not load. Is there a way to start these (maybe a service?) via shell script?

**Comment by guysoft** [comment]
This is known, it requires to change how the custom session starts on
pixel. Again, help would be great because I am busy with my startup company.

**Comment by guysoft** [comment]
New image ( 2016-11-25) was released, and has this written as a change: ``Updates to hardware video acceleration in Chromium browser``

http://downloads.raspberrypi.org/raspbian/release_notes.txt

Will build a nightly with it so we can see if it changes anything
