### ISSUE TITLE
It detects HDMI-CEC and can run netflix?

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [guysoft/FullPageOS#77]
It detects HDMI-CEC and can run netflix?

**Comment by guysoft** [comment]
1. I dont know
2. You are welcome to try this (last reply at the bottom): https://www.raspberrypi.org/forums/viewtopic.php?f=35&t=98559
I have no idea if it works, no netflix here.

**Comment by caio-ribeiro-pereira** [comment]
I tested week ago, and didn't support HDMI-CEC and no netflix because of DRM :(

**Comment by guysoft** [comment]
Might be relevant to add support now:
https://www.linuxuprising.com/2021/03/raspberry-pi-os-gets-official-widevine.html
