### ISSUE TITLE
Image files are unavailable

### ISSUE THREAD

**Issue by wackychocolatefactory** [guysoft/FullPageOS#85]
http://docstech.net/FullPageOS/ is returning a 403 error

However you can Google the URL and access the links the files through Google cache

http://docstech.net/FullPageOS/2015-05-05-fullpageos-wheezy-0.5.zip
http://docstech.net/FullPageOS/2016-05-10-fullpageos-jessie-lite-0.6.0.zip
http://docstech.net/FullPageOS/2016-07-20_2016-05-27-fullpageos-jessie-lite-0.7.0.zip

**Comment by guysoft** [comment]
Fixed :)
