### ISSUE TITLE
What am I missing on 2016-10-23_2016-09-23-fullpageos-jessie-0.7.0

### ISSUE THREAD

**Issue by jeffrolson** [guysoft/FullPageOS#88]
I'm not sure what I'm missing.
I'm running 2016-10-23_2016-09-23-fullpageos-jessie-0.7.0
Modified fullpageos-network.txt with my network ID and password.
It boots up into a raspberrian desktop and nothing more.
Network setting is not seen.
I manually set my network in the running os to what I listed in the fullpageos-network.txt file and reboot.  When it reloads I have network connectivity but i'm still not getting a browser to open and load any page I set in the /boot/fullpageos.txt
What am I missing.

**Comment by Symbiot78** [comment]
same here. 
try another build I think.

**Comment by guysoft** [comment]
Try 0.7.0 RC1

**Comment by guysoft** [comment]
Closing,  0.7.0 is out and no reply
