### ISSUE TITLE
Not going full screen - No refresh

### ISSUE THREAD

**Issue by jorgeiglesiasca** [guysoft/FullPageOS#9]
The page shown is maximized with only title bar and and the browser border visible.

Checked all the script files in the home folder and seems ok , tried to change kiosk mode to fullscreen mode in chromium but nothing happened. 

If i insert a keyboard and press F11 it goes correctly full screen.  Looks like the refreshing and F5 keystroke script written in the scripts folder are not working.

After some changes i installed again the untouched image in the SD card to see if something i´ve changed was forcing this issue but the problem seems to appear from scratch. On first boot the page goes maximized but not fullscreen.

 I couldnt check the refresh one after first boot because i have not internet connection.

**Comment by guysoft** [comment]
1. Can you please send a photo?
2. Did you modify anything?
3. The script that makes chrome go fullscreen is at ``/home/pi/scripts/fullscreen`` , can you execute that over SSH and report the result? No other windows should be open at boot..

**Comment by jorgeiglesiasca** [comment]
I made modifications but when i saw the border i wrote a new SD with fresh
system to check and browser border appears on first boot.

**Comment by guysoft** [comment]
@jorgeiglesiasca There is a new nightly build that might solve this:
http://docstech.net/FullPageOS/nightly/

**Comment by jorgeiglesiasca** [comment]
Tried nigthly but fullpageos-network file is missing in boot folder.   I added it manually , i inform just to add it in next releases.

**Comment by guysoft** [comment]
@jorgeiglesiasca did fullpageos-network work for you after added? Did not work for me.

**Comment by jorgeiglesiasca** [comment]
No. The system load diferent from before. No errors or warnings during
boot. After that a very long time of black screen and at the end raspbian
desktop.  No network working or browser load.

**Comment by guysoft** [comment]
This should be fixed in the last nightly,

**Comment by guysoft** [comment]
No response, tests show it works, and the refresh issue is addressed in #11
