### ISSUE TITLE
Chromium does not play mjpeg

### ISSUE THREAD

**Issue by graffmaxx** [guysoft/FullPageOS#91]
Hi there,

Does anyone know what packages are needed to enable mjpeg ipcam streams on chromium?
Currently i use an uv4l webrtc streaming server. If i open the adress on my notebook or tablet everything works fine. Also if i use a standard raspbian pixel image. But not if i use fullpageos. On this image i only see a white screen with a broken jpg symbol.

Thanks for help

**Comment by graffmaxx** [comment]
Forgot to say that it is a IP Cam

**Comment by guysoft** [comment]
Do you have a video example I can test on 0.7.0 RC1?
see #92

**Comment by graffmaxx** [comment]
Hi there,

i used the image "2016-10-20_2016-09-23-fullpageos-jessie-lite-0.7.0"
On this image i couldn't display any mjpeg stream in chromium.
You can try this URL. This one also didn't work: 

**http://www.ipcams.ch/WebCam.aspx?nr=856**

But now i fixed the issue by setting up my own Kiosk Image with your scripts and a original raspbian jessie pixel. Now everything works. 

I used your chroot_script and copy pasted every command expect the apt-get remove commands.

Maybe you remove to many libraries in the installation scripts?

**Comment by guysoft** [comment]
Hey, I just tested it on RC1 nightly and it works, use that.
