### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by zoesn89** [guysoft/FullPageOS#93]
Hey guys,
I managed everything I wanted to do with FullpageOS except to set german as the default language on my keyboard. I tried it with raspi-config AND by hand with sudo nano /etc/default/keyboard and setting XKBLAYOUT="gb" to XKBLAYOUT="de". But when I reboot, I have still the QWERTY keyboard. I use FullPageOS 0.7.0 RC1.
Can somebody help me please?
Tanks a lot! Keep up with your great project!

Felix

**Comment by guysoft** [comment]
You need to set the layout on lightdm. 
I haven't tried it, but according to this you need to set it here:
http://unix.stackexchange.com/questions/130858/change-the-keyboard-layout-in-lightdm

create ``/etc/X11/xorg.conf.d/20-keyboard.conf``. with the content:
```
Section "InputClass"
    Identifier "keyboard"
    MatchIsKeyboard "yes"
    Option "XkbLayout" "de"
    Option "XkbVariant" "nodeadkeys"
EndSection
```
