### ISSUE TITLE
Blank screen + 404 in FullPageDashboard

### ISSUE THREAD

**Issue by qriff** [guysoft/FullPageOS#97]
Running 2016-07-20_2016-05-27-fullpageos-jessie-lite-0.7.0 on Model B Revision 2.0 (512MB) results in everything booting ok (showing on monitor Debian booting normally, ssh ok) but blank monitor after booting.

And external browser shows http://192.168.x.x/FullPageDashboard with tabs themselves working but showing 404 for most webpages (if even that, mostly just white empty page).

**Comment by guysoft** [comment]
Fixed it? No wifi?

**Comment by qriff** [comment]
I've closen the issue immediately as I noticed the requirement is for Raspberry Pi 2.

On 19 January 2017 at 00:22, Guy Sheffer <notifications@github.com<mailto:notifications@github.com>> wrote:

Fixed it? No wifi?
