### ISSUE TITLE
Cant seem to get any website to load, except basic google search page.

### ISSUE THREAD

**Issue by ogbobby** [guysoft/FullPageOS#99]
i am using this version:2016-07-20_2016-05-27-fullpageos-jessie-lite-0.7.0.zip.
After config the wifi and adding just a basic page to fullpageos.txt, upon reboot it just boots to a google search page. Am i missing something?

**Comment by guysoft** [comment]
Can you paste your``fullpageos.txt``?

**Comment by ogbobby** [comment]
it just contains one url at the top:
http://www.runthejewels.com

This isnt the actually link i will be using it was just one i was testing.

**Comment by guysoft** [comment]
Ok, can you pate the output of:
``head -n 1 /boot/fullpageos.txt`` ?

**Comment by ogbobby** [comment]
http://www.runthejewels.com

**Comment by guysoft** [comment]
Can you really paste it? as in with the terminal output? I want to debug this.

**Comment by ogbobby** [comment]
im not sure how to do that when using putty ssh'd into the pi, can you tell me how. I apologize this is all pretty new to me.

**Comment by ogbobby** [comment]
Ok nevermind i think i got it. Thank you for helping and for your quick response and for all the work you have done to create this!!!!

**Comment by guysoft** [comment]
What was wrong?

**Comment by ogbobby** [comment]
It was my own dumb fault
